### PR TITLE
action: fix chaos workflow

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

fix chaos workflow failed due to version incompatibility.

### What is changed and how it works?

use the nightly image instead of latest.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Can we trigger it in pr first? Let's make sure it's ready to run correctly?

**Comment by 3AceShowHand** [comment]
> Can we trigger it in pr first? Let's make sure it's ready to run correctly?

I have verify it, it works.

**Review by hi-rustin — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
