### PR TITLE
tests: make integration test case http_api more stable

### LINKED ISSUE #2958: http_api flaking test
### Which jobs are flaking?

kafka integration test: http_api

### Which test(s) are flaking?

[2021-09-28T15:18:29.092Z] Traceback (most recent call last):

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 315, in <module>

[2021-09-28T15:18:29.092Z]     func(*sys.argv[2:])

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 92, in pause_changefeed

[2021-09-28T15:18:29.092Z]     assert resp.status_code == rq.codes.accepted

[2021-09-28T15:18:29.092Z] AssertionError

### Jenkins logs or GitHub Actions link

```log
[2021-09-28T15:18:25.029Z] *** etcd info ***:

[2021-09-28T15:18:25.029Z] 

[2021-09-28T15:18:25.029Z] /tidb/cdc/capture/2d6267f7-a019-4d58-995b-262a9e89d335

[2021-09-28T15:18:25.029Z] 	{"id":"2d6267f7-a019-4d58-995b-262a9e89d335","address":"127.0.0.1:8300","version":"v5.3.0-alpha-57-gc9fbc70b"}

[2021-09-28T15:18:25.029Z] 

[2021-09-28T15:18:25.029Z] /tidb/cdc/owner/22317c2cfbecc570

[2021-09-28T15:18:25.029Z] 	2d6267f7-a019-4d58-995b-262a9e89d335'

[2021-09-28T15:18:25.029Z] + grep -q 'etcd info'

[2021-09-28T15:18:25.029Z] + break

[2021-09-28T15:18:25.029Z] + set +x

[2021-09-28T15:18:26.938Z] pass test: check health

[2021-09-28T15:18:26.938Z] pass test: get status

[2021-09-28T15:18:27.196Z] pass test: create changefeed

[2021-09-28T15:18:28.574Z] pass test: list changefeed

[2021-09-28T15:18:28.833Z] pass test: get changefeed

[2021-09-28T15:18:29.092Z] Traceback (most recent call last):

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 315, in <module>

[2021-09-28T15:18:29.092Z]     func(*sys.argv[2:])

[2021-09-28T15:18:29.092Z]   File "/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/ticdc/tests/http_api/util/test_case.py", line 92, in pause_changefeed

[2021-09-28T15:18:29.092Z]     assert resp.status_code == rq.codes.accepted

[2021-09-28T15:18:29.092Z] AssertionError

[2021-09-28T15:18:51.030Z] make: *** [integration_test_kafka] Error 1
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
close #2958 

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
👍

**Review by amyangfei — APPROVED** [review]

**Comment by asddongmen** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/4126/pipeline 
The frequency of recent failures of this test is very high.

**Pull request merged**
