### PR TITLE
tests, dm/tests: fix sync_diff configs for CI

### LINKED ISSUE #3283: DM Binlog 999999 keeps failing
### Which jobs are flaking?

DM Binlog 999999 

### Which test(s) are flaking?

 dmctl test cmd: "start-task /tmp/dm_test/incremental_mode/dm-task.yaml "

### Jenkins logs or GitHub Actions link

```log
check diff failed 10-th time, retry later
check diff failed at last
Error: unknown keys in config file /home/runner/work/ticdc/ticdc/dm/tests/incremental_mode/conf/diff_config.toml: [log-level chunk-size sample-percent use-checksum fix-sql-file check-tables check-tables.schema check-tables.tables table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id target-db target-db.host target-db.port target-db.user target-db.password]
  -V, --version                  print version of sync_diff_inspector
  -L, --log-level string         log level: debug, info, warn, error, fatal (default "info")
  -C, --config string            Config file
      --dm-addr string           the address of DM
      --dm-task string           identifier of dm task
      --check-thread-count int   how many goroutines are created to check data (default 1)
      --export-fix-sql           set true if want to compare rows or set to false will only compare checksum (default true)
      --check-struct-only        ignore check table's data
...
```

https://github.com/pingcap/ticdc/runs/4099248345?check_suite_focus=true

### Anything else we need to know

- Does this test exist for other branches as well?
No
- Has there been a high frequency of failure lately?
From yesterday keeps failing.

### PR DESCRIPTION
**Pull request by Leavrth**
### What problem does this PR solve? 

sync_diff_spector's config has been updated.

close #3283 

### What is changed and how it works?

update sync_diff_spector's configs to v2.

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
CI still faild 🈚🈚
`failed to init Task: config changes breaking the checkpoint, please use another outputDir and start over again!`

@Leavrth thanks for your work, but perhaps you could try running a it-test on your local machine to get quick feedback

you can use cmd like `dm_integration_test CASE="openapi"` to test if the new sync_diff config is right

> run test need setup two mysql with different server id, see more [here](https://github.com/pingcap/ticdc/blob/master/dm/tests/README.md)

**Comment by lance6716** [comment]
```
flag provided but not defined: -log-level
```

in `upstream-database-switch`. This case reuses `incremental_mode` integration test plus changing upstream binlog file number to 999999

**Comment by Leavrth** [comment]
sync_diff_inspector in http://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz

```
version: 
sync_diff_inspector: v1.0.0~rc2+git.cccf51b
Git Commit Hash: cccf51b6f44cc6bbd96841d2fdc0c7bd9364ac69
UTC Build Time: 2020-02-27 05:46:50
Go Version: go1.13
```

**Comment by Leavrth** [comment]
CI pass https://github.com/pingcap/ticdc/pull/3295

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]

**Pull request merged**
