### PR TITLE
cdc/integration: Add unsigned test to row format

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

add unsigned type to `row format` integration test, to cover more cases.

### What is changed and how it works?

add unsigned for int / real table.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Comment by asddongmen** [comment]
@3AceShowHand Please fix it error.

**Review by overvenus — APPROVED** [review]

**Pull request merged**
