### PR TITLE
cli: make error message compatible with pd flag name

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/1893

### What is changed and how it works?

make error message compatible with pd flag name.

### Check List 

Tests 

None

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by hi-rustin** [comment]
cc: @ben1009  We missed this place in https://github.com/pingcap/ticdc/pull/2122. Could you please take a look? Thanks!

**Comment by ben1009** [comment]
> cc: @ben1009 We missed this place in #2122. Could you please take a look? Thanks!

seems already in master https://github.com/pingcap/ticdc/commit/d139b47f175c351e9b1a371da7cde44ee5b6ae7c ?

**Comment by hi-rustin** [comment]
> > cc: @ben1009 We missed this place in #2122. Could you please take a look? Thanks!
> 
> seems already in master [d139b47](https://github.com/pingcap/ticdc/commit/d139b47f175c351e9b1a371da7cde44ee5b6ae7c) ?

Are these two places?

**Comment by ben1009** [comment]
> > > cc: @ben1009 We missed this place in #2122. Could you please take a look? Thanks!
> > 
> > 
> > seems already in master [d139b47](https://github.com/pingcap/ticdc/commit/d139b47f175c351e9b1a371da7cde44ee5b6ae7c) ?
> 
> Are these two places?

wow, u are right

**Review by ben1009 — APPROVED** [review]

**Review by leoppro — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
