### PR TITLE
dm-test: fix unstable case

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve? 
fix unstable case [here](https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/434/pipeline/)

### What is changed and how it works?
run command with retry

reason see [this](https://github.com/pingcap/dm/pull/2225#issuecomment-951583877)

### Check List 

Tests 

 - No code

### Release note 
```release-note
`None`.
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
@lance6716 PTAL

**Comment by lance6716** [comment]
I prefer we update the error message as well

https://github.com/pingcap/ticdc/blob/e052c6aa1878130fccc296be861a4e8201cfcaac/dm/pkg/terror/error_list.go#L792

and maybe we can let Relay unit implement a `WaitUntil` in future PRs (please help file an issue)

https://github.com/pingcap/ticdc/blob/e052c6aa1878130fccc296be861a4e8201cfcaac/dm/dm/worker/subtask.go#L629

**Review by glorv — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]

**Comment by Ehco1996** [comment]
> I prefer we update the error message as well
> 
> https://github.com/pingcap/ticdc/blob/e052c6aa1878130fccc296be861a4e8201cfcaac/dm/pkg/terror/error_list.go#L792
> 
> and maybe we can let Relay unit implement a `WaitUntil` in future PRs (please help file an issue)
> 
> https://github.com/pingcap/ticdc/blob/e052c6aa1878130fccc296be861a4e8201cfcaac/dm/dm/worker/subtask.go#L629

we can disscuss this later, quick merge this pr for CI 😅😅

**Pull request merged**
