### PR TITLE
sink: fix codec json encoding with non binary string

### LINKED ISSUE #2758: json codec met panic: interface conversion: interface {} is string, not []uint8
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
panic: interface conversion: interface {} is string, not []uint8

goroutine 3552 [running]:
github.com/pingcap/ticdc/cdc/sink/codec.(*column).FromSinkColumn(0xc00e3c7b88, 0xc01f526e40)
	github.com/pingcap/ticdc/cdc/sink/codec/json.go:67 +0x357
github.com/pingcap/ticdc/cdc/sink/codec.sinkColumns2JsonColumns(0xc016bfda20, 0x16, 0x16, 0xc031903bc0)
	github.com/pingcap/ticdc/cdc/sink/codec/json.go:227 +0xaa
github.com/pingcap/ticdc/cdc/sink/codec.rowEventToMqMessage(0xc01f511000, 0xc00dd2a8c0, 0x4a4a368)
	github.com/pingcap/ticdc/cdc/sink/codec/json.go:215 +0x16e
github.com/pingcap/ticdc/cdc/sink/codec.(*JSONEventBatchEncoder).AppendRowChangedEvent(0xc00dd2a8c0, 0xc01f511000, 0x3, 0x2, 0x1)
	github.com/pingcap/ticdc/cdc/sink/codec/json.go:372 +0x43
github.com/pingcap/ticdc/cdc/sink.(*mqSink).runWorker(0xc00e72aea0, 0x2e57ba0, 0xc00e7b0940, 0x0, 0x0, 0x0)
	github.com/pingcap/ticdc/cdc/sink/mq.go:349 +0x3c0
github.com/pingcap/ticdc/cdc/sink.(*mqSink).run.func1(0x0, 0x0)
	github.com/pingcap/ticdc/cdc/sink/mq.go:279 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00d90fda0, 0xc00595ea40)
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 +0x66
```

 - resume changefeed can recover

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        ```
        v4.0.9
        ```

    - TiCDC version (execute `cdc version`):

        ```
        v4.0.12
        ```

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Close #2758

Note we still don't known in which scenario the column value is `string` instead of `[]byte`, need more investigation.

### What is changed and how it works?

The column value type of `mysql.TypeString`, `mysql.TypeVarString`, `mysql.TypeVarchar` could be either `string` or `[]byte`, we should consider both of these two types when converting a row column value to json encoding.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
Fix json encoding could panic when processing a string type value in some cases.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by overvenus** [comment]
Could you check type assertion in other files? To further prevent similar panics.

**Comment by amyangfei** [comment]
> Could you check type assertion in other files? To further prevent similar panics.

@overvenus .Good suggestion, I added a tracking issue. https://github.com/pingcap/ticdc/issues/2768

**Review by hi-rustin — APPROVED** [review]
👍

**Pull request merged**
