### PR TITLE
docs: update metrics dashboard and docs (#1584 & #1604 & #1640)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick (#1584 & #1604 & #1640) to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In ticdc repo:
git pr https://github.com/pingcap/ticdc/pull/1594
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/ticdc.git pr/1594:release-4.0-f86e3022303d
```

---

### What problem does this PR solve? 

update metrics dashboard and docs
### Check List 

Tests 

 - No code

### Release note

- No release note

### CODE REVIEW

**Review by leoppro — APPROVED** [review]

**Comment by amyangfei** [comment]
This cherry-pick has some conflicts. I suggest to merge metrics cherry-picks one by one

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
