### PR TITLE
readme: Update the expired docker-compose startup command

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/2082

### What is changed and how it works?

Use the correct file.
### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

None

### Release note

- No release note

### CODE REVIEW

**Comment by hi-rustin** [comment]
Tested in my local computer, no problem!

**Review by amyangfei — APPROVED** [review]

**Review by liuzix — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

Could you please help me merge this PR？ Thanks!

**Comment by amyangfei** [comment]
> /assign @amyangfei
> 
> Could you please help me merge this PR？ Thanks!

Find, we will merge this PR after some `release-blocker` is merged, since at 15:00 today release-5.1 will freeze code @hi-rustin

**Pull request merged**
