### PR TITLE
cli(fix): ignore the global flag for changefeed update command

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

close https://github.com/pingcap/ticdc/issues/2803
### What is changed and how it works?
ignore the global flag for changefeed update command

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch
 
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/uncc lonng

/cc @asddongmen 

Could you please take a look? Thanks!

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by 3AceShowHand** [comment]
LGTM

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
