### PR TITLE
test(pkg/cyclic): migrate test-infra to testify for pkg/cyclic pkg

### LINKED ISSUE #2869: migrate test-infra to testify for `pkg/cyclic` pkg

### LINKED ISSUE #2870: migrate test-infra to testify for `pkg/cyclic/mark` pkg

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve? 
migrate test-infra to testify for pkg/cyclic pkg,  close #2869  close #2870

### What is changed and how it works?

1. migrate test-infra from gocheck to testify
2. migrate leak test from leaktest to goleak

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
migrate test-infra to testify for pkg/cyclic pkg
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Comment by maxshuang** [comment]
@amyangfei  please help trigger merge, thanks

**Pull request merged**
