### PR TITLE
test: add workflow dispatch for github action

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
Currently if we want to trigger some github actiont test for some pr, we need change workflow file mannually and revert back before merge. This pr add workflow dispatch to manually run it.

### What is changed and how it works?
see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by GMHDBJD** [comment]
cc @lance6716 @lichunzhu 
You can try it in https://github.com/GMHDBJD/ticdc/actions/workflows/dm_chaos.yaml

**Pull request merged**
