### PR TITLE
refactor(cli): rewrite all cmds

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

cc: https://github.com/pingcap/ticdc/issues/2168

### What is changed and how it works?

Rewrite all cmds.

The adjustments are as follows:
1. 28 global variables were cleared
2. abstracted out the client construction factory for future refactoring
3. cleared all init methods
4. more standard flag collection
5. more standard parameter validation
6. go project compliant directory
7. better comment
8. cleaned up a lot of code that shouldn't appear in util

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by lonng** [comment]
This pull request is going to grow too large and prefer to split it into some smaller pull requests.

**Comment by hi-rustin** [comment]
> This pull request is going to grow too large and prefer to split it into some smaller pull requests.

Yes, after I finish the whole draft, I will try to split it. But it might be tougher because our original code is so coupled that it's hard to do a partial replacement. Maybe a possible solution would be for me to submit the code independently by module, but also keep the old code, and then delete and clean up the old code after the new code is finally all submitted. I'll think of a better way to do this during the refactoring process. Thank you for the reminder.

**Comment by hi-rustin** [comment]
checklists
- [ ] Guaranteed minimal visibility
- [ ] Note the init method migration
- [ ] Ensure that common parameters do not affect other commands
- [ ] Ensure that clients are not created repeatedly

**Comment by ben1009** [comment]
Take my knees

**Comment by hi-rustin** [comment]
/hold

Never merge it. I will split it.

**Comment by hi-rustin** [comment]
/close

Almost done!

**Pull request closed without merging**
