### PR TITLE
pkg,sorter(ticdc): gather fs related functions

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Gather fs related functions 

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by liuzix — APPROVED** [review]

**Comment by amyangfei** [comment]
please resolve conflicts

**Review by asddongmen — APPROVED** [review]

**Comment by overvenus** [comment]
Test fails due to flakey tests https://github.com/pingcap/ticdc/issues/3815

**Pull request merged**
