### PR TITLE
owner: prevent table start-ts regressions (#1236)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1236 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In ticdc repo:
git pr https://github.com/pingcap/ticdc/pull/1331
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/ticdc.git pr/1331:release-4.0-78de95e14e1f
```

---

### What problem does this PR solve? 
- The start-ts of a table could regress if the table is added to a capture whose current checkpoint-ts is less than the start-ts of said table, and before the checkpoint-ts catches up, the capture exits abnormally. This regression, in rare cases, could cause the start-ts to regress so far that it is earlier than the global checkpoint-ts. When this happens, SchemaStorage related errors occur. #1258 #1235 

### What is changed and how it works?
- Fixed several bugs in Owner so that never will a local checkpoint be less than the global checkpoint.
- Cleaned up checkpoint ts semantics with respect to DDL operations, so that a DDL is finished **if and only if** `global checkpoint >= FinishTs`.
- Fixed a bug in processor introduced by #1247 which causes local checkpoint regression.
- Added Etcd state checker to integration test.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- Fix bugs in the owner that could lead to abnormal CDC server exits during table migrations.

### CODE REVIEW

**Comment by liuzix** [comment]
This cherry-pick depends on #1323

**Comment by amyangfei** [comment]
> This cherry-pick depends on #1323

PTAL @liuzix

**Comment by liuzix** [comment]
Will cherry pick manually

**Pull request closed without merging**
