### PR TITLE
config(ticdc): add column-selectors for sink and split config file

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
part of https://github.com/pingcap/ticdc/issues/3082

### What is changed and how it works?
- add column_selectors field
- split config

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @ben1009 @overvenus 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by overvenus — APPROVED** [review]
LGTM

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
