### PR TITLE
dm: revert dm#2048

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve? 
Revert dm#2048 due to #3487

Also cherry-pick #3413 #3435 #3471 to make integration stable.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
LGTM

the difference of this revert PR and dm#2048 is https://github.com/pingcap/dm/pull/2047/files#diff-e725a03bd475dc4ea28028613ede1fd88a8cc8f881f0a1788a189e766f191830R1869

after this PR, we reset streamer to `s.checkpoint.GlobalPoint()` but before dm#2048, we reset streamer to `lastLocation`.

`s.checkpoint.GlobalPoint()` is updated in three places: xid job, ddl job, handle-error skip. In the first two places `lastLocation` is equal to `s.checkpoint.GlobalPoint()`. In the last place `s.checkpoint.GlobalPoint()` is forwarded, I think it's better than `lastLocation` because we now remember user's action after ResetReplicationSyncer

**Comment by GMHDBJD** [comment]
> after this PR, we reset streamer to s.checkpoint.GlobalPoint() but before dm#2048, we reset streamer to lastLocation.
One situation is sequence sharding ddl, lastLocation is forwarded but global checkpoint is not, may this cause some problem? 🤔
rest LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
> LGTM
> 
> the difference of this revert PR and dm#2048 is https://github.com/pingcap/dm/pull/2047/files#diff-e725a03bd475dc4ea28028613ede1fd88a8cc8f881f0a1788a189e766f191830R1869
> 
> after this PR, we reset streamer to `s.checkpoint.GlobalPoint()` but before dm#2048, we reset streamer to `lastLocation`.
> 
> `s.checkpoint.GlobalPoint()` is updated in three places: xid job, ddl job, handle-error skip. In the first two places `lastLocation` is equal to `s.checkpoint.GlobalPoint()`. In the last place `s.checkpoint.GlobalPoint()` is forwarded, I think it's better than `lastLocation` because we now remember user's action after ResetReplicationSyncer

We may also update `lastLocation` when handle-error skip, in this way lastLocation will represent `last finished binlog` accurately. We can optimize this later.

**Pull request merged**
