### PR TITLE
s3Sink: cancel create existing table directory on s3 when initialize s3Sink

### PR DESCRIPTION
**Pull request by dengqee**
s3Sink: cancel create existing table directory on s3 when initialize s3Sink

fix bug [#1463](https://github.com/pingcap/ticdc/issues/1463) reported

### What problem does this PR solve? 
fix bug [#1463](https://github.com/pingcap/ticdc/issues/1463) reported

### What is changed and how it works?
https://github.com/pingcap/ticdc/blob/355016c0ee9d689fe203db57a18449afe26271d9/cdc/sink/cdclog/s3.go#L318-L327
S3 does not create an empty directory. This code causes S3 to create objects instead of directories, like this:
image

Uploading objects to these directories will cause an error, like:
```sell
"code": "CDC:ErrProcessorUnknown",
"message": "[CDC:ErrS3SinkStorageAPI]XMinioParentIsObject: Object-prefix is already an object, please choose a different object-prefix name.\n\tstatus code: 400, request id: 166825DDCC17A799, host id: "
```
So I deleted the code.
### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 

Side effects

 - Possible performance regression
 

Related changes

 - Need to cherry-pick to the release branch

### Release note
- s3Sink:  cancel create existing table directory on s3 when initialize s3Sink to avoid uploading objects faild

### CODE REVIEW

**Comment by dengqee** [comment]
@3pointer @amyangfei @leoppro PTAL

**Comment by dengqee** [comment]
@3pointer @amyangfei @leoppro PTAL

**Review by amyangfei — COMMENTED** [review]
When uploading a file such as `t_60/cdclog.xxxxxxxx`, will the directory `t_60` be created automatically.
Besides, could you please add this case to existing integration test `tests/cdclog_s3`

**Comment by dengqee** [comment]
> Thanks!
> I have a question about the behavior of S3, when uploading a file such as `t_60/cdclog.xxxxxxxx`, will the directory `t_60` be created automatically?
> Besides, could you please add this case to existing integration test `tests/cdclog_s3`

Yes, S3 will create  the directory`t_60` automatically when upload a file like `t_60/cdclog.xxxxxxxx`. And if you delete all files in a directory on S3, the directory will be deleted automatically.
I will try to add this case to integration test.

**Review by amyangfei — COMMENTED** [review]
LGTM

**Comment by dengqee** [comment]
@3pointer  @leoppro PTAL

**Comment by dengqee** [comment]
@3pointer PTAL

**Comment by 3pointer** [comment]
LGTM

**Pull request merged**
