### PR TITLE
tests: add leak test in all unit test cases (#1078)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1078 to release-4.0

---

### What problem does this PR solve? 

Add a leak test 

### What is changed and how it works?

- Use TiDB leak test library
- Add leak test in every unit test entry
- Fix several goroutine leaks in unit test

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
Need resolve conflicts

**Comment by overvenus** [comment]
LGTM

**Pull request merged**
