### PR TITLE
*: update tidb and tikv/client-go

### PR DESCRIPTION
**Pull request by disksing**
### What problem does this PR solve? 
Update tidb and client-go to latest master. Adapt changes about code refactoring.
Import BR inside pingcap/tidb.

### Check List 

Tests 
 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by disksing** [comment]
seems something is wrong with go mod cache :(

**Comment by amyangfei** [comment]
Could you please add `protoc` version in `proto/generate-proto.sh` @disksing

**Review by amyangfei — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
