### PR TITLE
version(ticdc): fix wrong version of ChangefeedStateFromAdminJob gate

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

We were using the wrong version. It should be `v4.0.15`.

### What is changed and how it works?

Fix wrong version and only use lessThan API.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

None

Related changes

 - Need to cherry-pick to the release branch (I will do it manually.)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @asddongmen 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
