### PR TITLE
cli(refactor): add cli cmds for processor, tso and unsafe

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

part of #2168

cc: #2199

split from #2262

### What is changed and how it works?

add cli processor cmd

### Check List 

Tests 

None

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/unhold 

Ready for review.

**Review by overvenus — APPROVED** [review]

**Comment by hi-rustin** [comment]
/cc @amyangfei 

Could you please take a look? Thanks!

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
