### PR TITLE
lint: bump lint version and remove useless tools and test code

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?

bump lint version and remove useless tools and test code.

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

/cc

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

I will use this PR to test region_merge issue.

**Comment by hi-rustin** [comment]
/auto-cc

/unhold

Ready for review!

**Comment by hi-rustin** [comment]
/cc @amyangfei 

Could you please take a look? Thanks!

**Review by overvenus — APPROVED** [review]
Awesome!

**Pull request merged**
