### PR TITLE
tests: fix mock server sends event before kv client is ready

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Fix unstable unit test

```
[2021-04-21T06:27:22.638Z] [2021/04/21 14:26:58.418 +08:00] [ERROR] [client_v2.go:81] ["received an event but neither pending region nor running region was found"] [regionID=3] [requestID=61] [addr=127.0.0.1:15936] [stack="github.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).sendRegionChangeEventV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:81\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).receiveFromStreamV2\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go:274\ngithub.com/pingcap/ticdc/cdc/kv.(*eventFeedSession).dispatchRequest.func1\n\t/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client.go:815\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57"]
[2021-04-21T06:27:22.638Z] 
[2021-04-21T06:27:22.638Z] ----------------------------------------------------------------------
[2021-04-21T06:27:22.638Z] FAIL: client_test.go:1306: etcdSuite.TestStreamRecvWithErrorAndResolvedGoBack
[2021-04-21T06:27:22.639Z] 
[2021-04-21T06:27:22.639Z] client_test.go:1347:
[2021-04-21T06:27:22.639Z] client_test.go:239:
[2021-04-21T06:27:22.639Z]     s.c.Assert(err, check.IsNil)
[2021-04-21T06:27:22.639Z] ... value *status.statusError = &status.statusError{Code:1, Message:"context canceled", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0} ("rpc error: code = Canceled desc = context canceled")
[2021-04-21T06:27:22.639Z] 
[2021-04-21T06:27:22.639Z]     c.Assert(errors.Cause(err), check.Equals, context.Canceled)
[2021-04-21T06:27:22.639Z] ... obtained *errors.Error = &errors.Error{code:0, codeText:"CDC:ErrNoPendingRegion", message:"received event regionID %v, requestID %v from %v, but neither pending region nor running region was found", redactArgsPos:[]int(nil), cause:error(nil), args:[]interface {}{0x3, 0x3d, "127.0.0.1:15936"}, file:"/home/jenkins/agent/workspace/cdc_ghpr_leak_test/go/src/github.com/pingcap/ticdc/cdc/kv/client_v2.go", line:85} ("[CDC:ErrNoPendingRegion]received event regionID 3, requestID 61 from 127.0.0.1:15936, but neither pending region nor running region was found")
[2021-04-21T06:27:22.639Z] ... expected *errors.errorString = &errors.errorString{s:"context canceled"} ("context canceled")
```

### What is changed and how it works?

The root cause is new request ID is allocated in kv client first, and then pending region is inserted, when the test code detects request ID is ready, the pending region could be not ready.
This is a fix for the test

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
ptal @liuzix @JinLingChristopher

**Review by lance6716 — APPROVED** [review]

**Comment by leoppro** [comment]
we should try to simplify testing of kvclient, but LGTM

/lgtm

**Pull request merged**
