### PR TITLE
owner: fix owner tick block http request

### LINKED ISSUE #3483: http api “api/v1/changefeeds” was refused by owner when cdc cluster is rolling update
### What did you do?

1. Update cdc version one by one in cdc cluster
2. Query changefeed status in the middle of rolling update:
curl -X GET http://172.16.6.140:8300/api/v1/changefeeds
（owner is 5.3.0-master，other is 5.2.1）

### What did you expect to see?

query successfully on owner

### What did you see instead?

```
[maxshuang@copy-of-vm-ee-centos76-v1 tidb_cluster]$ curl -X GET http://172.16.6.140:8300/api/v1/changefeeds
{
    "error_msg": "context deadline exceeded",
    "error_code": ""
}

[maxshuang@copy-of-vm-ee-centos76-v1 tidb_cluster]$ curl -X GET http://172.16.6.140:8301/api/v1/changefeeds
[
    {
        "id": "kv-reconn",
        "state": "normal",
        "checkpoint_tso": 429141621833990146,
        "checkpoint_time": "2021-11-16 14:49:31.376",
        "error": {
            "addr": "172.16.6.140:8300",
            "code": "CDC:ErrOwnerUnknown",
            "message": "[CDC:ErrReachMaxTry]reach maximum try: 20: [CDC:ErrMySQLTxnError]Error 1049: Unknown database 'workload': Error 1049: Unknown database 'workload'"
        }
    }
```

It seems that owner refuses to serve the http request.  Is it acceptable?    

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
5.2.1
```

TiCDC version (execute `cdc version`):

```console
5.3.0-master
```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
close #3483 

### What is changed and how it works?

Move `o.handleJobs()` before this check:
```go
	if !o.clusterVersionConsistent(state.Captures) {
		// sleep one second to avoid printing too much log
		time.Sleep(1 * time.Second)
		return state, nil
	}
```

The `http_handler` in master branch is now get / put data from `status_provider` interface, which comunicate with the owner directly through `pushOwnerJob` method provided by the owner. And all owner jobs will be handle in the owner's `tick` logic. So, if the `tick` was blocked by  the version check mentioned above,  the owner jobs willl never be handle until timeout.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
 - Unit Test

Code changes

Side effects

Related changes

### Release note 

```release-note
Fix HTTP API not working when there are TiCDC nodes of different versions in one cdc cluster.
```

### CODE REVIEW

**Comment by liuzix** [comment]
And you try to a a unit tests for this case?

**Comment by asddongmen** [comment]
> And you try to a a unit tests for this case?

I will do this.

**Review by amyangfei — COMMENTED** [review]
Please add a release note

**Comment by asddongmen** [comment]
@liuzix ut added, PTAL.

**Review by liuzix — APPROVED** [review]

**Comment by asddongmen** [comment]
@3AceShowHand PTAL~

**Comment by 3AceShowHand** [comment]
please make the release note more concise, and can you add some comments about cautions for this change?

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
