### PR TITLE
tests: fix unstable integration_test gc_safepoint

### LINKED ISSUE #2653: check_safepoint_forward in integration test gc_safepoint is not correct
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

   Run integration test (gc_safepoint) and met following error

```
[2021-08-27T03:10:11.472Z] [Fri Aug 27 11:10:10 CST 2021] <<<<<< START cdc server in gc_safepoint case >>>>>>
[2021-08-27T03:10:11.472Z] + [[ '' == \t\r\u\e ]]
[2021-08-27T03:10:11.472Z] + cdc cli --pd http://127.0.0.1:2379 changefeed list
[2021-08-27T03:10:11.472Z] + GO_FAILPOINTS='github.com/pingcap/ticdc/cdc/owner/InjectGcSafepointUpdateInterval=return(500)'
[2021-08-27T03:10:11.472Z] + cdc.test -test.coverprofile=/tmp/tidb_cdc_test/cov.gc_safepoint.17601767.out server --log-file /tmp/tidb_cdc_test/gc_safepoint/cdc.log --log-level debug --sorter-num-workerpool-goroutine 4 --data-dir /tmp/tidb_cdc_test/gc_safepoint/cdc_data --addr 127.0.0.1:8300 --pd http://127.0.0.1:2379
[2021-08-27T03:10:11.472Z] Error: TiCDC cluster is unknown, please start TiCDC cluster
[2021-08-27T03:10:11.472Z] Usage:
[2021-08-27T03:10:11.472Z]   cdc cli changefeed list [flags]
[2021-08-27T03:10:11.472Z] 
[2021-08-27T03:10:11.472Z] Flags:
[2021-08-27T03:10:11.472Z]   -a, --all    List all replication tasks(including removed and finished)
[2021-08-27T03:10:11.472Z]   -h, --help   help for list
[2021-08-27T03:10:11.472Z] 
[2021-08-27T03:10:11.472Z] Global Flags:
[2021-08-27T03:10:11.472Z]       --ca string          CA certificate path for TLS connection
[2021-08-27T03:10:11.472Z]       --cert string        Certificate path for TLS connection
[2021-08-27T03:10:11.472Z]   -i, --interact           Run cdc cli with readline
[2021-08-27T03:10:11.472Z]       --key string         Private key path for TLS connection
[2021-08-27T03:10:11.472Z]       --log-level string   log level (etc: debug|info|warn|error) (default "warn")
[2021-08-27T03:10:11.472Z]       --pd string          PD address, use ',' to separate multiple PDs (default "http://127.0.0.1:2379")
[2021-08-27T03:10:11.473Z] 
[2021-08-27T03:10:11.473Z] TiCDC cluster is unknown, please start TiCDC cluster
[2021-08-27T03:10:11.473Z] + i=1
[2021-08-27T03:10:11.473Z] + '[' 1 -gt 50 ']'
[2021-08-27T03:10:11.473Z] + sleep 3
[2021-08-27T03:10:14.002Z] + cdc cli --pd http://127.0.0.1:2379 changefeed list
[2021-08-27T03:10:14.002Z] []
[2021-08-27T03:10:14.002Z] + set +x
[2021-08-27T03:10:15.379Z] check diff failed 1-th time, retry later
[2021-08-27T03:10:17.917Z] check diff failed 2-th time, retry later
[2021-08-27T03:10:19.819Z] check diff failed 3-th time, retry later
[2021-08-27T03:10:22.352Z] check diff failed 4-th time, retry later
[2021-08-27T03:10:24.887Z] check diff failed 5-th time, retry later
[2021-08-27T03:10:26.794Z] check diff successfully
[2021-08-27T03:10:26.794Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:27.734Z] safepoint 427303586827862020 is not forward
[2021-08-27T03:10:27.734Z] run task failed 1-th time, retry later
[2021-08-27T03:10:30.270Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:30.841Z] safepoint 427303587090006021 is not forward
[2021-08-27T03:10:30.841Z] run task failed 2-th time, retry later
[2021-08-27T03:10:32.747Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:34.123Z] safepoint 427303587876438020 is not forward
[2021-08-27T03:10:34.123Z] run task failed 3-th time, retry later
[2021-08-27T03:10:36.026Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:36.965Z] safepoint 427303588662870020 is not forward
[2021-08-27T03:10:36.965Z] run task failed 4-th time, retry later
[2021-08-27T03:10:38.868Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:40.244Z] safepoint 427303589449302020 is not forward
[2021-08-27T03:10:40.244Z] run task failed 5-th time, retry later
[2021-08-27T03:10:42.153Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:43.088Z] safepoint 427303590235471876 is not forward
[2021-08-27T03:10:43.088Z] run task failed 6-th time, retry later
[2021-08-27T03:10:44.997Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:45.942Z] safepoint 427303591021903876 is not forward
[2021-08-27T03:10:45.942Z] run task failed 7-th time, retry later
[2021-08-27T03:10:48.480Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:49.053Z] safepoint 427303591808335876 is not forward
[2021-08-27T03:10:49.053Z] run task failed 8-th time, retry later
[2021-08-27T03:10:51.596Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:52.166Z] safepoint 427303592595030020 is not forward
[2021-08-27T03:10:52.166Z] run task failed 9-th time, retry later
[2021-08-27T03:10:54.084Z] check_safepoint_forward http://127.0.0.1:2379 7000941764186010867
[2021-08-27T03:10:55.463Z] safepoint 427303594167894019 is not forward
[2021-08-27T03:10:55.463Z] run task failed 10-th time, retry later
[2021-08-27T03:10:57.372Z] run task failed
```

   The safepoint is forwarded actually, but the detector reports false positive.

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/142ae26b291df8ca8ce8cb8286b2d92f87a261d4

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve? 
close #2653 

### What is changed and how it works?
record start_safepoint before check_safepoint_forward

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Side effects

None

Related changes

 None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
> [CLA assistant check](https://cla-assistant.io/pingcap/ticdc?pullRequest=2717)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/ticdc?pullRequest=2717) before we can accept your contribution.
> **CharlesCheung** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/ticdc?pullRequest=2717) it.

@CharlesCheung96 Could you please sign the cla?

**Review by amyangfei — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
