### PR TITLE
cmd: remove default sink-uri and check for empty sink-uri before trying to create sink (#1155)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1155 to release-4.0

---

### What problem does this PR solve? 
- CDC previously has a default sink-uri `mysql://123456:root@127.0.0.1:3306`, and this should have been removed.

### What is changed and how it works?
- Changed the default sink-uri to the empty string.
- Check for empty sink-uri before creating sink.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
Please resolve merge conflicts @liuzix

**Pull request merged**
