### PR TITLE
config: Add log configuration items to the config file

### PR DESCRIPTION
**Pull request by SuperSupeng**
### What problem does this PR solve? 
Add log configuration items to the config file. #1384 

### What is changed and how it works?
Add logFileMaxSize, logFileMaxDays and logFileMaxBackups items when load config file.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by SuperSupeng** [comment]
#2317 PR was closed for compatibility reasons. The configuration file is in this form to try to keep the TiCDC as consistent as possible with the TIDB configuration.

**Review by overvenus — APPROVED** [review]
LGTM

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
