### PR TITLE
DNM: test resolve lock

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### CODE REVIEW

**Comment by amyangfei** [comment]
Could TiCDC CI pass when using TiDB in https://github.com/pingcap/tidb/pull/22723?

**Comment by sticnarf** [comment]
No, the test is actually not compatible with async commit. We should adjust the test.

**Pull request closed without merging**
