### PR TITLE
test: fix TestStreamSendWithError unstable test

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

partof  https://github.com/pingcap/ticdc/issues/2289
### What is changed and how it works?

Shouldn't we be asserting the send error, which is the purpose of this test to change it?

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

/cc

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

[I added the other error on the issue](https://github.com/pingcap/ticdc/issues/2289#issuecomment-902406201) and I think we can merge this change first. We'll see if we encounter the same problem I encountered locally later.

Could you please help me trigger the merge process? Thanks!

**Pull request merged**
