### PR TITLE
test(ticdc): separate statistics for unit tests and integration tests

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
part of https://github.com/pingcap/ticdc/issues/3569

### What is changed and how it works?
separate statistics for unit tests and integration tests.

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by hi-rustin** [comment]
/run-kafka-integration-test

😢

**Comment by hi-rustin** [comment]
/run-kafka-integration-test

😢 network issue

**Comment by hi-rustin** [comment]
/run-kafka-integration-test

😢 network issue

**Pull request merged**
