### PR TITLE
cmd: hide --sort-dir in changefeed command. (deprecated warning exists)

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Hide `--sort-dir` in changefeed command

### What is changed and how it works?

- Hide `--sort-dir` in changefeed command
- Set `SortDir` to `` `json:"-"` `` in changefeed, so the `changefeed query` won't print any `sort-dir` which may confuse user. Note only set it to an ignore field is **backward compatibility**

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by leoppro — APPROVED** [review]

**Review by lonng — COMMENTED** [review]
/lgtm

**Pull request merged**
