### PR TITLE
github workflow: add a auto assign bug github action

### PR DESCRIPTION
**Pull request by ben1009**
### What problem does this PR solve? 
auto run issues assignment to project Question and Bug Reports Kanban

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
Small question, how can we verify this PR can work?

**Comment by ben1009** [comment]
> Small question, how can we verify this PR can work?

without merge to master, i have no idea, but it works in tikv https://github.com/tikv/tikv/pull/7752, so could give a try

**Review by overvenus — APPROVED** [review]

**Pull request merged**
