### PR TITLE
sorter: fix memory leak in memoryBackEnd

### PR DESCRIPTION
**Pull request by liuzix**
### What problem does this PR solve? 
- When the sorter is using memory to sort, the sorter will internally hold a reference to events that have  already been output to the sink. This will delay the recycling of the `PolymorphicEvent` objects by GC, causing increased memory use.

Cc https://github.com/pingcap/ticdc/issues/2553

### What is changed and how it works?
- `memoryBackEnd` now eagerly clears references to events not needed any more.

### Check List 

Tests 

 - Unit test

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
Optimize memory management when unified sorter is using memory to sort.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM, I confirm it fixes memory leak.

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-010d7333-7fff-271d-fb0e-d48662ecb5d2"><div dir="ltr" style="margin-left:0pt;" align="left">

This fix | Without this fix
-- | --
image | image
image |image  

</div></b>

**Review by ben1009 — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
leak test failed

```
[2021-08-30T07:20:23.606Z] WARNING: Error cleaning up temporaries: openfdat /tmp/check-468093389971413028/4/tmp/sorter: permission denied
[2021-08-30T07:20:23.606Z] ----------------------------------------------------------------------
[2021-08-30T07:20:23.606Z] FAIL: memory_backend_test.go:29: memoryBackendSuite.TestNoLeaking
[2021-08-30T07:20:23.606Z] 
[2021-08-30T07:20:23.606Z] memory_backend_test.go:64:
[2021-08-30T07:20:23.606Z]     c.Assert(atomic.LoadInt64(&objCount), check.Equals, int64(0))
[2021-08-30T07:20:23.606Z] ... obtained int64 = 454
[2021-08-30T07:20:23.606Z] ... expected int64 = 0
[2021-08-30T07:20:23.606Z] 
```

**Pull request merged**
