### PR TITLE
docs:  update verify-ci trigger commands

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

as title

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡 @lance6716 @okJiang

**Review by lance6716 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
