### PR TITLE
build: update tidb/pd/parser dep to latest release-5.0

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

update tidb/pd/parser dep to latest release-5.0

### What is changed and how it works?

update tidb/pd/parser dep to latest release-5.0

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
/hold
merge this PR after other release-blocker is merged, in case of go module conflicts

**Review by leoppro — APPROVED** [review]

**Pull request merged**
