### PR TITLE
github: enable concurrency mode

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

Turn on concurrency mode to reduce the waste of resources in GitHub actions.

### What is changed and how it works?

Turn on concurrency mode to reduce the waste of resources in GitHub actions.

See also: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
can you add this for chaos.yaml ?

**Comment by hi-rustin** [comment]
> can you add this for chaos.yaml ?

Chaos is not running on PR, so it shouldn't be needed?

**Review by lance6716 — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
> > can you add this for chaos.yaml ?
> 
> Chaos is not running on PR, so it shouldn't be needed?

got it, thx

**Pull request merged**
