### PR TITLE
puller/sorter: remove manual GC settings

### LINKED ISSUE #2202: Unified sorter manual GC may pause all goroutines and cause gRPC keepalive dog timeout
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Running a changefeed that captures 6k tables.

| With Unified Sorter | W/O Unified Sorter|
|--|--|
|image|image|
|25s|7s|

By removed these lines, TiCDC backs to normal.

https://github.com/pingcap/ticdc/blob/284dd55766f4f57b4c3550057c219bd1c92e5331/cdc/puller/sorter/backend_pool.go#L136-L146

2. What did you expect to see?

No keepalive dog timeout.

3. What did you see instead?

keepalive dog timeout

4. Versions of the cluster

release-5.0 and release-5.1

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Do not change default GC settings, it could reduce the minimum mutator utilization and lead to #2202.

Close #2202 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Capturing 6k tables.

Related changes

 - Need to cherry-pick to the release branch

### Release note

```release-note
Fix gRPC keepalive error when memory pressure is high.
```

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
The trace result from #2202 shows the GC pause time reduces from 25s to 7s after turning off gc percent adjust. However `7s` is still quite a long GC pause time. Is there any more PRs to address this problem.

**Comment by overvenus** [comment]
> The trace result from #2202 shows the GC pause time reduces from 25s to 7s after turning off gc percent adjust. However `7s` is still quite a long GC pause time. Is there any more PRs to address this problem.

7s pause is likely caused by memory leak with new ower enabled, here is the issue https://github.com/pingcap/ticdc/issues/2212

**Review by liuzix — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Comment by amyangfei** [comment]
This pr will be evaluated by more tests

**Comment by overvenus** [comment]
I am going to merge this PR. Tests (https://github.com/pingcap/ticdc/pull/2699#issue-724007913) show without changing default GC setting, TiCDC can handle 140G incremental data (no OOM).

**Pull request merged**
