### PR TITLE
scripts: support specify tidb/pd/tikv version in test

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Support specify tidb/pd/tikv version in test

### What is changed and how it works?

use example:
`/run-integration-tests tikv=release-4.0` or `/run-integration-tests tikv=pr/xxx`

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=release-4.0 tikv=release-4.0 pd=release-4.0

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by amyangfei** [comment]
/run-integration-tests tidb=v4.0.0-beta.2 tikv=v4.0.0-beta.2 pd=v4.0.0-beta.2

**Comment by leoppro** [comment]
LGTM

**Pull request merged**
