### PR TITLE
dm/worker: don't exit when failed to read checkpoint in relay

### LINKED ISSUE #3344: DM-worker can't boot up when it's assigned relay and can't connect downstream
### What did you do?

1. start-relay -s source1 worker1
2. start a task of source1
3. kill downstream
4. restart worker1

### What did you expect to see?

worker1 is started and report friendly error

### What did you see instead?

worker1 will exit after a short time

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
5.3.0
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #3344 

### What is changed and how it works?

ignore the error when failed to "get min location from checkpoint"

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch **(?)**

### Release note 

```release-note
Fix a bug that DM-worker can't boot up after restart
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Comment by GMHDBJD** [comment]
What about other errors？https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L286
https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L297
https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L314
https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L328
https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L338

**Comment by lance6716** [comment]
> What about other errors？
> 
> https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L286
> 
> 
> https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L297
> 
> 
> https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L314
> 
> 
> https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L328
> 
> 
> https://github.com/pingcap/ticdc/blob/6a506af6c11623eed13f0957e1f379eec8e4b342/dm/dm/worker/source_worker.go#L338

they're mostly caused by "can connect to etcd of DM master",

`Relay.Init` error is fixed in https://github.com/pingcap/dm/pull/2227

`binlog.ExtractSuffix` is a logic error so we should not ignore IMO 🤔

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
