### PR TITLE
*: upgrade TiDB to fix resolving async-commit locks bug

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### What problem does this PR solve? 

Upgrade TiDB dependency to fix https://github.com/pingcap/tidb/issues/24384.

### What is changed and how it works?

Upgrade TiDB dependency to fix https://github.com/pingcap/tidb/issues/24384.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
please fix ci

**Comment by youjiali1995** [comment]
It can pass on my laptop.
image

**Comment by amyangfei** [comment]
Is it related with golang version?

**Comment by youjiali1995** [comment]
For https://github.com/pingcap/ticdc/pull/1729/checks?check_run_id=2524782747, I used the same version Go(go1.16.3) and golangci-lint(v1.30.0).

**Comment by overvenus** [comment]
Looks like it's a duplicate of https://github.com/pingcap/ticdc/pull/1727.

**Comment by youjiali1995** [comment]
> Looks like it's a duplicate of #1727.

Yes! I can close mine.

**Comment by youjiali1995** [comment]
gg

**Pull request closed without merging**
