### PR TITLE
*: enable unparam static check

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

part of https://github.com/pingcap/ticdc/issues/2162
### What is changed and how it works?
enable unparam static check and refine codes

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by hi-rustin** [comment]
/label require-LGT1

Marking the change requires only one 👍 because it is simple and does not modify any logic.

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
/assign @overvenus 

Could you please help me trigger the merge process? This PR only require one LGTM.

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
💚 💙 💜 💛 ❤️
Thanks for your review!

**Comment by hi-rustin** [comment]
Conflicts resolved, could you help re-trigger the merge?

**Pull request merged**
