### PR TITLE
*:refine log output

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
#1765  
#1762 
#1761 

### What is changed and how it works?

Appropriate log output is added(#1765) and redundant log output is removed(#1761 #1762).

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

1.For #1765 , the out put now is as below: 
```
$ cdc cli changefeed query -c ttl-test-12
>
[2021/05/14 11:47:30.324 +08:00] [ERROR] [client_changefeed.go:218] ["This changefeed does not exist"] [changefeed=ttl-test-12]
Error: [CDC:ErrChangeFeedNotExists]changefeed not exists, key: /tidb/cdc/job/ttl-test-12
Usage:
  cdc cli changefeed query [flags]

Flags:
  -c, --changefeed-id string   Replication task (changefeed) ID
  -h, --help                   help for query
  -s, --simple                 Output simplified replication status

Global Flags:
      --ca string          CA certificate path for TLS connection
      --cert string        Certificate path for TLS connection
  -i, --interact           Run cdc cli with readline
      --key string         Private key path for TLS connection
      --log-level string   log level (etc: debug|info|warn|error) (default "warn")
      --pd string          PD address, use ',' to separate multiple PDs (default "http://127.0.0.1:2379")

[CDC:ErrChangeFeedNotExists]changefeed not exists, key: /tidb/cdc/job/ttl-test-12
```

2. For #1761 the out put now is as below:
```
$ cat ticdc2.log | grep 'get clusterID' | wc -l
0
```

3. For #1762 the out put now is as below:
```
cat tmp1.log | grep -E 'merger exiting|Merger has exited' | wc -l
6

[2021/05/14 12:12:38.589 +08:00] [INFO] [merger.go:66] ["Unified Sorter: merger exiting, cleaning up resources"]
[pending-set-size=1]
[2021/05/14 12:12:48.592 +08:00] [INFO] [merger.go:66] ["Unified Sorter: merger exiting, cleaning up resources"]
[pending-set-size=0]
...

```
Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by lonng** [comment]
@hi-rustin Can bot remove the `ptal` automatically while adding tag `status/LGT2`?

**Comment by hi-rustin** [comment]
> @hi-rustin Can bot remove the `ptal` automatically while adding tag `status/LGT2`?

This feature is not available yet. Because patl is added manually. So the bot doesn't know to remove it yet. But we should automate the process. You are able to create an issue at https://github.com/ti-community-infra/tichi. We will improve this feature later.

**Pull request merged**
