### PR TITLE
*: fix dml not replicate when add partition about partition table without valid index

### PR DESCRIPTION
**Pull request by erwadba**
### What problem does this PR solve? 

#2834
When `force-replicate` is enabled. Add partition on partition table without valid index. The cdc will stop dml replication about the partition table without errors and warnings.

### Check List 

Tests 

 - N/A

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - N/A

### Release note 

```release-note
Fix dml is not replicated after adding partition in partition table without valid index
```

### CODE REVIEW

**Review by liuzix — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
LGTM, thanks!

**Comment by amyangfei** [comment]
Unit test or integration test will be added in another PR, followed up in https://github.com/pingcap/ticdc/issues/2834#issuecomment-922171333

**Pull request merged**
