### PR TITLE
*: strict fmt (#1181)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1181 to release-4.0

---

### What problem does this PR solve? 

Strict fmt TiCDC code base.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
This cheery-pick has a lot of conflicts, would you please resolve them @overvenus

**Review by leoppro — APPROVED** [review]

**Pull request merged**
