### PR TITLE
tests(ticdc): set up the sync diff output directory correctly

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
Use the same directory as the log.

### What is changed and how it works?
set up the sync diff output directory correctly. Move it into `/tmp/tidb_cdc_test/`.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @asddongmen @ben1009 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by hi-rustin** [comment]
/unhold

/assign @overvenus 

Could you please help me trigger the merge process again? Thanks!

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
