### PR TITLE
dm/test: align test behaviour for enable-relay

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
fix upstream_switch CI is broken after https://github.com/pingcap/ticdc/pull/3190

https://github.com/pingcap/ticdc/pull/3190#issuecomment-968677147

### What is changed and how it works?

fix CI

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
seems fixed https://github.com/pingcap/ticdc/runs/4209747770?check_suite_focus=true

@GMHDBJD

**Review by D3Hunter — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
