### PR TITLE
api: move the API specs file into right place

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

part of https://github.com/pingcap/ticdc/issues/2199

### What is changed and how it works?

 move the API specs file into right place. See: https://github.com/golang-standards/project-layout/tree/master/api

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note

None

```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/cc @amyangfei 

Could you please take a look? Thanks!

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
