### PR TITLE
puller,kv: trivial fix for puller

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
trivial fix for puller:
1. refine comments
2. remove useless field
3. refine the impl order

### Check List 

Tests 

 - No code (Comments and useless code)

Code changes

None

Side effects
None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @3AceShowHand @asddongmen 

Could you please take a look? Thanks!

**Review by overvenus — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
