### PR TITLE
metrics: correct TiKV CDC endpoint CPU

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Corrects TiKV CDC endpoint CPU

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch

### Release note

- Correct TiKV CDC endpoint CPU metric in TiCDC dashboard.

### CODE REVIEW

**Comment by liuzix** [comment]
What did we exclude by changing `cdc.*` to `cdc_.*`?

**Comment by overvenus** [comment]
> What did we exclude by changing `cdc.*` to `cdc_.*`?

The thread name has been changed to `cdc_[0-9]+`.

**Comment by amyangfei** [comment]
Also needs to cherry-pick 4.0?

**Review by amyangfei — APPROVED** [review]

**Comment by overvenus** [comment]
> Does this need to cherry-pick 4.0?

release-4.0 still use "cdc". I will add cherry-pick 4.0 too, and check if we need to adjust the expression too.

**Pull request merged**
