### PR TITLE
scripts: clean up unused pipeline files

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

cc: https://github.com/pingcap/ticdc/issues/2353

### What is changed and how it works?

clean up unused pipeline files.

These files have been migrated to https://github.com/PingCAP-QE/ci/tree/main/jenkins/pipelines/ci/ticdc.

### Check List 

Tests 

None

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### CODE REVIEW

**Comment by hi-rustin** [comment]
Since it's just deleting files, I marked it as only needing one 👍.

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
