### PR TITLE
tests: clean old owner integration tests

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
#2574 

### Check List 

Tests 

 - Unit test
 - Integration test

Side effects

 - Breaking backward compatibility

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
Do we need to clean up comments like new owner and new processor?

rest LGTM.

**Comment by asddongmen** [comment]
> Do we need to clean up comments like new owner and new processor?
> 
> rest LGTM.

done

**Pull request merged**
