### PR TITLE
test: make unit test fail fast

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
make unit test fail fast

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by amyangfei** [comment]
How does this parameter work, when I add a fake failure in test such as `c.Assert(false, check.IsTrue)`, the test seems not terminate

```
âžœ  make unit_test
# use -mod=mod to avoid error: missing go.sum entry for module providing package
# ref: https://github.com/golang/go/issues/44129
which bin/failpoint-ctl >/dev/null 2>&1 || CGO_ENABLED=0 GO111MODULE=on go build  -trimpath -mod=mod -o bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl && go mod tidy
./scripts/fix_lib_zstd.sh
rm: cannot remove â€˜zstd_cgo.goâ€™: No such file or directory
mkdir -p "/tmp/tidb_cdc_test"
$(echo $(for p in $(go list ./...| grep -vE 'vendor|proto|ticdc\/tests|integration|testing_utils'); do echo ${p#"github.com/pingcap/ticdc/"}|grep -v "github.com/pingcap/ticdc"; done) | xargs bin/failpoint-ctl enable >/dev/null)
ok      github.com/pingcap/ticdc/cdc    53.066s coverage: 27.6% of statements
?       github.com/pingcap/ticdc/cdc/capture    [no test files]

----------------------------------------------------------------------
FAIL: codec_test.go:33: codecSuite.TestDecodeRecordKey

codec_test.go:44:
    c.Assert(false, check.IsTrue)
... obtained bool = false

OOPS: 12 passed, 1 FAILED
--- FAIL: Test (68.56s)
FAIL
coverage: 56.5% of statements
FAIL    github.com/pingcap/ticdc/cdc/entry      69.356s
ok      github.com/pingcap/ticdc/cdc/kv 172.969s        coverage: 69.5% of statements
ok      github.com/pingcap/ticdc/cdc/model      0.542s  coverage: 80.3% of statements
ok      github.com/pingcap/ticdc/cdc/owner      31.181s coverage: 85.0% of statements
ok      github.com/pingcap/ticdc/cdc/processor  0.648s  coverage: 58.0% of statements
ok      github.com/pingcap/ticdc/cdc/processor/pipeline 47.174s coverage: 53.6% of statements
```
@hi-rustin

**Comment by hi-rustin** [comment]
> How does this parameter work, when I add a fake failure in test such as `c.Assert(false, check.IsTrue)`, the test seems not terminate
> 
> ```
> âžœ  make unit_test
> # use -mod=mod to avoid error: missing go.sum entry for module providing package
> # ref: https://github.com/golang/go/issues/44129
> which bin/failpoint-ctl >/dev/null 2>&1 || CGO_ENABLED=0 GO111MODULE=on go build  -trimpath -mod=mod -o bin/failpoint-ctl github.com/pingcap/failpoint/failpoint-ctl && go mod tidy
> ./scripts/fix_lib_zstd.sh
> rm: cannot remove â€˜zstd_cgo.goâ€™: No such file or directory
> mkdir -p "/tmp/tidb_cdc_test"
> $(echo $(for p in $(go list ./...| grep -vE 'vendor|proto|ticdc\/tests|integration|testing_utils'); do echo ${p#"github.com/pingcap/ticdc/"}|grep -v "github.com/pingcap/ticdc"; done) | xargs bin/failpoint-ctl enable >/dev/null)
> ok      github.com/pingcap/ticdc/cdc    53.066s coverage: 27.6% of statements
> ?       github.com/pingcap/ticdc/cdc/capture    [no test files]
> 
> ----------------------------------------------------------------------
> FAIL: codec_test.go:33: codecSuite.TestDecodeRecordKey
> 
> codec_test.go:44:
>     c.Assert(false, check.IsTrue)
> ... obtained bool = false
> 
> OOPS: 12 passed, 1 FAILED
> --- FAIL: Test (68.56s)
> FAIL
> coverage: 56.5% of statements
> FAIL    github.com/pingcap/ticdc/cdc/entry      69.356s
> ok      github.com/pingcap/ticdc/cdc/kv 172.969s        coverage: 69.5% of statements
> ok      github.com/pingcap/ticdc/cdc/model      0.542s  coverage: 80.3% of statements
> ok      github.com/pingcap/ticdc/cdc/owner      31.181s coverage: 85.0% of statements
> ok      github.com/pingcap/ticdc/cdc/processor  0.648s  coverage: 58.0% of statements
> ok      github.com/pingcap/ticdc/cdc/processor/pipeline 47.174s coverage: 53.6% of statements
> ```
> 
> @hi-rustin

 The new go test -failfast flag disables running additional tests after any test fails. Note that tests running in parallel with the failing test are allowed to complete.

Maybe because they are tests that run in parallel?

**Comment by hi-rustin** [comment]
/close 

@amyangfei 

https://github.com/golang/go/issues/33038

It really doesn't work. 😢 I am stupid!

**Pull request closed without merging**
