### PR TITLE
test(pkg/errors): migrate test-infra to testify for pkg/errors pkg

### LINKED ISSUE #2871: migrate test-infra to testify for `pkg/errors` pkg

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve? 
migrate test-infra to testify for pkg/errors pkg, close #2871 

### What is changed and how it works?

1. migrate test-infra from gocheck to testify
2. migrate leak test from leaktest to goleak

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
migrate test-infra to testify for pkg/errors pkg
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by maxshuang** [comment]
@3AceShowHand @hi-rustin    hi folks,   PTLA  when available, thanks

**Review by ben1009 — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
@amyangfei Could you please help trigger the merge process? Thanks! 💚 💙 💜 💛 ❤️

**Comment by maxshuang** [comment]
@amyangfei  please help merge if u r free

**Pull request merged**
