### PR TITLE
kv/client: fix token counter in region scan limiter

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

- Fix token is not correctly updated in some corner case
- Add more metrics

### What is changed and how it works?

- Fix token is not correctly updated in some corner case
- Add more metrics
- Fix a bug that context is not used correctly when calling `onRegionFail`, which may lead to region loss, the error region should be re-dispatched, but ignore in error channel. (This Fix has been verified by manual test in the next part)

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
   - Setup a cdc replication cluster with 3 TiKVs, in the upstream prepare more than 10k regions.
   - Reload one of the TiKV
   - The resolved ts of TiCDC should recovery in 2 minutes.

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
/run-all-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Comment by amyangfei** [comment]
/run-integration-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Review by overvenus — APPROVED** [review]

**Review by leoppro — APPROVED** [review]

**Pull request merged**
