### PR TITLE
[DNM] enable clustered index by default

### PR DESCRIPTION
**Pull request by YuJuncen**
### What problem does this PR solve? 
Nothing, just for testing.

### What is changed and how it works?
Enable clustered index by default, so we can run cases in CI and see what happened.

### Release note
- No release note

### CODE REVIEW

**Comment by YuJuncen** [comment]
`tests/cdc` failed, with data lose `[2021-03-16T06:08:50.406Z] [2021/03/16 14:08:49.343 +08:00] [WARN] [diff.go:182] ["table struct is not equal"] [reason="column num not equal, one is 34 another is 2"]`.

I'm not sure whether this is clustered index relative.

[cdc 2.log](https://github.com/pingcap/ticdc/files/6146611/cdc.2.log)

**Comment by YuJuncen** [comment]
```
[2021-03-18T06:39:55.435Z] [Thu Mar 18 14:39:55 CST 2021] Executing SQL: SET GLOBAL tidb_enable_clustered_index = 1;
[2021-03-18T06:40:00.678Z] [Thu Mar 18 14:40:00 CST 2021] Executing SQL: use test;drop table if exists foooooo;create table foooooo(pk1 int, pk2 int, primary key (pk1, pk2) );insert into foooooo values(42, 42), (89, 89)
[2021-03-18T06:40:01.241Z] [Thu Mar 18 14:40:00 CST 2021] Executing SQL: select table_name, tidb_pk_type from information_schema.tables where table_schema = 'test';
[2021-03-18T06:40:01.241Z] *************************** 1. row ***************************
[2021-03-18T06:40:01.241Z]   table_name: foooooo
[2021-03-18T06:40:01.241Z] tidb_pk_type: NON-CLUSTERED
```
🤔

**Comment by hi-rustin** [comment]
/close

Please feel free to re-open the PR if you still need to test it. Thank you!

**Pull request closed without merging**
