### PR TITLE
tests: use normal mysql user in integration test

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Close item-1 in https://github.com/pingcap/ticdc/issues/1748

### What is changed and how it works?

- Create a normal MySQL user in the integration tests.
- The privilege of MySQL user is `select,insert,update,delete,index,create,drop,alter,create view`

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by overvenus — COMMENTED** [review]
/lgtm

**Comment by amyangfei** [comment]
ptal @leoppro @liuzix

**Review by leoppro — APPROVED** [review]

**Pull request merged**
