### PR TITLE
cli: better prompting for flags that cannot be updated

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

part of https://github.com/pingcap/ticdc/issues/2803

### What is changed and how it works?
ignore the global flag for changefeed update command

### Check List 

Tests 

Manual testing.

Code changes

None

Side effects

None

Related changes

 -  [ ] pushed to https://github.com/pingcap/ticdc/pull/2832

### Release note 

```release-note
better prompting for flags that cannot be updated
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
which we use here https://github.com/pingcap/ticdc/blob/a7bb6c47cfba8996980b8d29bb156ae9225c7a3f/pkg/cmd/cli/cli_changefeed_update.go#L180. so it should be passable.

**Comment by amyangfei** [comment]
Should this be picked to `release-5.2`

**Comment by hi-rustin** [comment]
> Should this PR be picked to `release-5.2`

image

**Comment by amyangfei** [comment]
> > Should this PR be picked to `release-5.2`
> 
> image

Get confused with too many PRs, seems `release-5.2` should pick both #2827 and this PR. 😵

**Comment by hi-rustin** [comment]
> 
> Get confused with too many PRs, seems `release-5.2` should pick both #2827 and this PR. 😵

Yes, I'm going to put it together. Sorry for not being clear.

**Review by amyangfei — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

Could you please help trigger the merge process? Thanks!

**Pull request merged**
