### PR TITLE
security(dm): fix some security problems

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 
fix https://github.com/pingcap/ticdc/issues/3666

### What is changed and how it works?

change file mode

after this patch, gosec would not complain anymore
```
Summary:
  Gosec  : 2.9.3
  Files  : 269
  Lines  : 94482
  Nosec  : 0
  Issues : 0
```

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
```

[2021-11-30T10:01:55.060Z]         {

[2021-11-30T10:01:55.060Z]             "result": false,

[2021-11-30T10:01:55.060Z]             "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:28001 ErrClass:\"relay-event-lib\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"parse server-uuid.index\" RawCause:\"open relay-dir/server-uuid.index: permission denied\" , Workaround: Please execute `query-status` to check status.",

[2021-11-30T10:01:55.060Z]             "source": "mysql-replica-01",

[2021-11-30T10:01:55.060Z]             "worker": "worker1"

[2021-11-30T10:01:55.060Z]         }

[2021-11-30T10:01:55.060Z]     ]

[2021-11-30T10:01:55.060Z] }
```

need fix this

**Review by lance6716 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
