### PR TITLE
owner(ticdc): correctly handle the state after the old owner is upgraded to the new owner

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
part of  https://github.com/pingcap/ticdc/issues/3473

### What is changed and how it works?
correctly display the status of the old owner's paused tasks.

### Check List 

Tests 

- [x] Manual testing
- [ ] Test infra testing?
- [x] unit tests

Code changes

None

Side effects

None
Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
Fix the problem of changefeed resuming automatically after upgrading cluster
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

Waiting for test.

**Review by liuzix — COMMENTED** [review]
Can we have integration tests for this?

**Comment by hi-rustin** [comment]
> Can we have integration tests for this?

I will try to add a test case on test-infra.

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
/hold

I'll probably write a better solution. See https://docs.google.com/document/d/1ex7PQ8AWtdpFf5VMJ9-TMdk4xM5m1S68tkP6aKYHR60/edit#heading=h.rtyrqbrdc0zd for a specific discussion (in Chinese).

**Pull request closed without merging**
