### PR TITLE
feat: basic implementation of exchange partition

### PR DESCRIPTION
**Pull request by BowenXiao1999**
### What problem does this PR solve? 
#639 

### What is changed and how it works?
add type mode.ActionExchangePartition logic in schemastorage.go

### Check List 

Tests 

 - Unit test (pass unit test in changed directory)
 - Integration test (not able to test #716 )

Code changes

 - Has exported function/method change

Side effects

 - Possible performance regression

### Release note

- processor: support simple exchange partition support

Is there a CONTRIBUTING.md?

### CODE REVIEW

**Comment by BowenXiao1999** [comment]
This is my idea for implementation: https://github.com/pingcap/ticdc/issues/639#issuecomment-654216419
Plz point out my mistake if any.

**Comment by amyangfei** [comment]
> Plz point out my mistake if any.

Have replied in the given issue.

**Comment by ben1009** [comment]
is this pr still active for review, thanks

**Comment by hi-rustin** [comment]
@BowenXiao1999 Can you resolve the conflict, please? That way we can move forward with PR, but it's okay if you don't continue working on it. Thank you for your contribution! 💚 💙 💜 💛 ❤️

**Comment by hi-rustin** [comment]
/close

I am closing this PR because it has not been updated for a long time.
Please feel free to contact me to reopen the PR if you have time to finish it. 
Thank you very much for your contribution!

**Pull request closed without merging**
