### PR TITLE
docs: fix typo in design of new processor

### PR DESCRIPTION
**Pull request by ben1009**
### What problem does this PR solve? 
fix typo in new processor doc

### Check List 

Related changes

 - Need to cherry-pick to the release branch

### Release note
No release note

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by overvenus** [comment]
/lgtm

PR title should follow https://github.com/pingcap/community/blob/master/contributors/commit-message-pr-style.md

**Review by lonng — COMMENTED** [review]
/lgtm

**Comment by lonng** [comment]
@ben1009 I think the PR description should be refined and delete some useless list item.

**Pull request merged**
