### PR TITLE
capture: fix incorrect session aliveness detection (#1237)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1237 to release-5.0-rc

---

### What problem does this PR solve? 

Fix https://github.com/pingcap/ticdc/issues/1234

### What is changed and how it works?

This is part 1 of #1234 
- [x] fix incorrect session aliveness detection by querying lease TTL
- [ ] more observations will be added in another PR

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- Fix a bug that cdc server could exit unexpected when meeting ErrTaskStatusNotExists and the capture session is disconnected at the same time.

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Comment by overvenus** [comment]
LGTM

**Comment by amyangfei** [comment]
Close since we have created a new `release-5.0` branch from master

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
