### PR TITLE
integration_tests(ticdc): move integration tests into integration_tests dir

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
part of https://github.com/pingcap/ticdc/issues/2199

### What is changed and how it works?
move integration tests into integration_tests dir.
Other test-related files will be moved to this directory later.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @amyangfei @overvenus 

Integration tests passed!

**Comment by hi-rustin** [comment]
/hold

blocked by https://github.com/PingCAP-QE/ci/pull/484

**Review by overvenus — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
/unhold

https://github.com/PingCAP-QE/ci/pull/484 merging.

**Pull request merged**
