### PR TITLE
[DNM]codec: fix canal mysql type.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Comment by 3AceShowHand** [comment]
run-all-tests

**Review by lonng — COMMENTED** [review]
@3AceShowHand Can you refine your pull request description?

**Comment by 3AceShowHand** [comment]
duplicate of #3677

**Pull request closed without merging**
