### PR TITLE
doc: change readme support Go version to Go >= 1.16

### PR DESCRIPTION
**Pull request by ben1009**
### What problem does this PR solve? 
fix readme Go version Go >= 1.16. we update to go 1.6.4 https://github.com/pingcap/ticdc/pull/1818, but ticdc is no longer compatible with go version >= 1.13 after  #2109

image

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### Release note

- No release note

### CODE REVIEW

**Comment by ben1009** [comment]
why change in README.md need run xxx-tests, and cause `idc-jenkins-ci/leak-test` fail 😡

**Review by lonng — COMMENTED** [review]
/lgtm

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by amyangfei** [comment]
Note the incompatible with go1.13 is not caused by #1818, but caused by #2109

**Review by amyangfei — APPROVED** [review]

**Comment by ben1009** [comment]
> Note the incompatible with go1.13 is not caused by #1818, but caused by #2109

agree, i updated the description to provide more info, thx

**Pull request merged**
