### PR TITLE
cmd: fix pd parameter in update config

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Fix a new bug introduced by #1554

### What is changed and how it works?

- `--pd` parameter should be ignored
- other unsupported parameter doesn't panic, log a warnning

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by leoppro — COMMENTED** [review]
/lgtm

**Comment by amyangfei** [comment]
@leoppro  please comment `/lgtm` or use review `approve`,
review with `/lgtm` doesn't work. ref: https://book.prow.tidb.io/#/en/plugins/lgtm

**Pull request merged**
