### PR TITLE
tests: fix more events could be sent after a table is removed

### LINKED ISSUE #2500: unit test managerSuite.TestManagerAddRemoveTable is not stable
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

```
[2021-08-11T05:52:24.019Z] 
[2021-08-11T05:52:24.019Z] ----------------------------------------------------------------------
[2021-08-11T05:52:24.019Z] FAIL: manager_test.go:138: managerSuite.TestManagerAddRemoveTable
[2021-08-11T05:52:24.019Z] 
[2021-08-11T05:52:24.019Z] manager_test.go:62:
[2021-08-11T05:52:24.019Z]     c.Assert(row.CommitTs, check.Greater, c.lastResolvedTs)
[2021-08-11T05:52:24.019Z] ... compare_one uint64 = 0x2a9
[2021-08-11T05:52:24.019Z] ... compare_two uint64 = 0x2bc
[2021-08-11T05:52:24.019Z] 
[2021-08-11T05:52:24.019Z] [2021/08/11 13:46:15.865 +08:00] [ERROR] [mysql.go:1064] ["execute DMLs failed"] [err="[CDC:ErrMySQLTxnError]Error 1049: "] [stack="github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql.go:1064\ngithub.com/pingcap/ticdc/cdc/sink.MySQLSinkSuite.TestExecDMLRollbackErrDatabaseNotExists\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql_test.go:1265\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:476\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:337\ngithub.com/pingcap/check.(*suiteRunner).forkTest.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850\ngithub.com/pingcap/check.(*suiteRunner).forkCall.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739"]
[2021-08-11T05:52:24.019Z] [2021/08/11 13:47:56.736 +08:00] [ERROR] [mysql.go:1064] ["execute DMLs failed"] [err="[CDC:ErrReachMaxTry]reach maximum try: 8"] [stack="github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql.go:1064\ngithub.com/pingcap/ticdc/cdc/sink.MySQLSinkSuite.TestExecDMLRollbackErrRetryable\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql_test.go:1403\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:476\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:337\ngithub.com/pingcap/check.(*suiteRunner).forkTest.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850\ngithub.com/pingcap/check.(*suiteRunner).forkCall.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739"]
[2021-08-11T05:52:24.019Z] [2021/08/11 13:47:56.744 +08:00] [ERROR] [mysql.go:1064] ["execute DMLs failed"] [err="[CDC:ErrMySQLTxnError]Error 1146: "] [stack="github.com/pingcap/ticdc/cdc/sink.(*mysqlSink).execDMLs\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql.go:1064\ngithub.com/pingcap/ticdc/cdc/sink.MySQLSinkSuite.TestExecDMLRollbackErrTableNotExists\n\t/home/jenkins/agent/workspace/cdc_ghpr_test/go/src/github.com/pingcap/ticdc/cdc/sink/mysql_test.go:1333\nreflect.Value.call\n\t/usr/local/go/src/reflect/value.go:476\nreflect.Value.Call\n\t/usr/local/go/src/reflect/value.go:337\ngithub.com/pingcap/check.(*suiteRunner).forkTest.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:850\ngithub.com/pingcap/check.(*suiteRunner).forkCall.func1\n\t/nfs/cache/mod/github.com/pingcap/check@v0.0.0-20200212061837-5e12011dc712/check.go:739"]
[2021-08-11T05:52:24.019Z] [mysql] 2021/08/11 13:47:59 packets.go:36: read tcp 127.0.0.1:52428->127.0.0.1:33333: i/o timeout
[2021-08-11T05:52:24.019Z] [mysql] 2021/08/11 13:48:01 packets.go:36: read tcp 127.0.0.1:52704->127.0.0.1:33333: i/o timeout
[2021-08-11T05:52:24.019Z] [mysql] 2021/08/11 13:48:03 packets.go:36: read tcp 127.0.0.1:52846->127.0.0.1:33333: i/o timeout
[2021-08-11T05:52:24.019Z] OOPS: 31 passed, 1 FAILED
[2021-08-11T05:52:24.019Z] --- FAIL: Test (113.86s)
[2021-08-11T05:52:24.019Z] FAIL
[2021-08-11T05:52:24.019Z] coverage: 64.7% of statements
```

2. Versions of the cluster

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/1800517e6aad32bd5bb80fd7893d89c4dfc7cac2

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Close #2500

The test failure is caused by sending more row changed events to backend sink when a table sink is removed, the close channel way can't terminate table sink at once.

### What is changed and how it works?

Use the context to control table sink lifecycle.

### Check List 

Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
Unstable test fixer! 👍

**Review by overvenus — APPROVED** [review]

**Pull request merged**
