### PR TITLE
dm/election: fix datarace when campaign slow

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/3495

### What is changed and how it works?

use `campaignMu` to protect `e.campaignWg`

In the for loop, campaignWg.Add(1) and cancelCampaign was assigned.

But in the test, Resign was called in another thread, and cancelCampaign was used in Resgin which race with campaignWg.Add(1) in the for loop.

### Check List 

Tests 

 - Unit test

Code changes

- None

Side effects

 - Possible performance regression

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by okJiang** [comment]
Can you explain the cause of the problem? The original [link](ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_test/detail/cdc_ghpr_test/12109/pipeline) has expired and cannot be traced

**Comment by Ehco1996** [comment]
> Can you explain the cause of the unstable UT? The original [link](ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_test/detail/cdc_ghpr_test/12109/pipeline) has expired and cannot be traced.

see here, https://github.com/pingcap/ticdc/issues/3495

**Review by okJiang — APPROVED** [review]
In the for loop, `campaignWg.Add(1)` and `cancelCampaign` was assigned.

But in the test, Resign was called in another thread, and cancelCampaign was used in Resgin which race with `campaignWg.Add(1)` in the for loop.

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
