### PR TITLE
owner: fix owner ship metrics

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
owner: fix owner ship metrics

### Check List 

Tests 

 - Unit test
### Release note

- No release note

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by liuzix — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
/run-all-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Review by ben1009 — APPROVED** [review]
`Files errors.toml and /tmp/errors.toml.before differ`
need regen the errdoc

**Comment by amyangfei** [comment]
/run-integration-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Comment by amyangfei** [comment]
/run-integration-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Comment by leoppro** [comment]
/run-integration-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Comment by leoppro** [comment]
/run-integration-tests /tidb=release-5.0 /tikv=release-5.0 /pd=release-5.0 /tiflash=release-5.0

**Pull request merged**
