### PR TITLE
sink(ticdc): add TestSetParams test

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
 * add TestSetParams test for canal JSON encoder.

* refine some code order.

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects
None
Related changes

 None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @3AceShowHand @liuzix 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by 3AceShowHand — APPROVED** [review]

**Review by overvenus — APPROVED** [review]
LGTM

**Pull request merged**
