### PR TITLE
sorter(ticdc): remove useless field

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
remove useless field. There seems to be no need to save this global variable in struct.

### Check List 

Tests 

 - No code(remove field)

Code changes

None

Side effects
None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @liuzix 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by lance6716 — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @lance6716 

Could you please help me trigger the merge process? Thanks!  💚 💙 💜 💛 ❤️

**Pull request merged**
