### PR TITLE
metrics: update TiKV metrics

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve? 

Update TiKV graphs to display recently added metrics.

image
image
image

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note

- No release note

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by leoppro** [comment]
please remember to update metrics docs @overvenus

**Pull request merged**
