### PR TITLE
cli: add noArgs to all commands

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
#2303 

### What is changed and how it works?
add noArgs to all commands 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM, though it looks like conflicting with https://github.com/pingcap/ticdc/pull/2696

**Comment by asddongmen** [comment]
old cli in maste branch  has been delete

**Comment by hi-rustin** [comment]
> The old cli in maste branch has been deleted.
> I have opened a new PR #2742 to 5.1 branch.

@asddongmen Thanks! I will modify the new cli to support these parameters as well.

**Pull request closed without merging**
