### PR TITLE
kv: enable use new kv client in release-4.0

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

This is a subtask of #2765, enable new kv client in release-4.0 

### Check List 

Tests 

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by overvenus** [comment]
Please check commits in this page, and make sure related tests and functions are enabled. https://github.com/pingcap/ticdc/commits/release-4.0?after=ee5ac462ce3b0efcb9fc3f7faa5e81af4421a016+80&branch=release-4.0

**Review by asddongmen — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
