### PR TITLE
puller: clean up unused parameter

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

Follow up https://github.com/pingcap/ticdc/pull/2271

### What is changed and how it works?

clean up unused parameter.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

 None

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Comment by amyangfei** [comment]
Is there any linter in `golangci-lint` to check this pattern?

**Review by amyangfei — APPROVED** [review]

**Review by overvenus — APPROVED** [review]

**Comment by hi-rustin** [comment]
/run-all-tests

/assign @overvenus 

Could you please help me trigger the merge process?

**Pull request merged**
