### PR TITLE
sink: remove cdclog.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

This PR remove all `cdclog` related code, include `S3Sink` and `fileSink`.

### What is changed and how it works?

* remove all related code and test cases.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
The code change looks good.

1. please fill in the description of pr
2. please remove the corresponding integration test

**Review by overvenus — COMMENTED** [review]
After addressing https://github.com/pingcap/ticdc/pull/3599#pullrequestreview-814356317, LGTM

**Review by overvenus — APPROVED** [review]
LGTM

**Comment by hi-rustin** [comment]
image

The description here also needs to be handled. Let me change it for you.

**Review by hi-rustin — APPROVED** [review]

**Comment by leoppro** [comment]
LGTM from PM. We can withdraw the `cdclog` sink.

**Comment by dengqee** [comment]
Can I ask why you removed `cdclog` sink?

**Comment by amyangfei** [comment]
This feature will not be maintained in the latest version, would you please give more details from the view of product @leoppro ?

**Comment by coderplay** [comment]
The same question here. Why you guys removed it?

**Pull request merged**
