### PR TITLE
github: use x64 self runner for build and check job

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

cc: https://github.com/pingcap/ticdc/issues/3173

### What is changed and how it works?

use x64 self runner for build and check job. We still have a heavy queue at the moment.
10 min -> 1 min
### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

None
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @overvenus @lance6716 

10 min -> 1 min , We have 12 available x64 self runners!

Could you please take a look? Thanks!

**Review by overvenus — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @lance6716 

Could you please help me trigger the merge process? Thanks!

**Pull request merged**
