### PR TITLE
capture: refine some comments and simplify IsOwner func

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None.

### What is changed and how it works?

refine some comments and simplify IsOwner func.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

There are still some to-do's. I will try to figure out why, so if you have any ideas, please feel free to comment.

**Comment by hi-rustin** [comment]
/unhold

/label require-LGT1

Marking this PR requires only one LGTM because this change is simple.

**Comment by hi-rustin** [comment]
The CI failed:  https://github.com/pingcap/ticdc/issues/2650

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
