### PR TITLE
*: fix wrong timezone when env `TZ` is not set

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
If the environment `TZ` is not set , the value of `time.Local.String()` is `Local`, 
when we try to connect to mysql using `Local` timezone, we will get an error: `Error 1298: Unknown or incorrect time zone: 'Local'`

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by amyangfei** [comment]
I found in some environment without `TZ` env, using `timezone="Local"` can be success, sounds strange.
```
[2020/04/28 16:22:00.429 +08:00] [INFO] [mysql.go:341] ["Start mysql sink"] [dsn="root@tcp(127.0.0.1:3306)/?interpolateParams=true&loc=Local&multiStatements=true&time_zone=%22Local%22"]
```

**Comment by amyangfei** [comment]
BTW, is the `loc` variable needed in `DSN`, as we don't provide `parseTime=true`

**Comment by leoppro** [comment]
> I found in some environment without `TZ` env, using `timezone="Local"` can be success, sounds strange.
> 
> ```
> [2020/04/28 16:22:00.429 +08:00] [INFO] [mysql.go:341] ["Start mysql sink"] [dsn="root@tcp(127.0.0.1:3306)/?interpolateParams=true&loc=Local&multiStatements=true&time_zone=%22Local%22"]
> ```

Is the downstream is TiDB?

`Error 1298: Unknown or incorrect time zone: 'Local'` this error is reported by `MySQL`

**Comment by amyangfei** [comment]
> > I found in some environment without `TZ` env, using `timezone="Local"` can be success, sounds strange.
> > ```
> > [2020/04/28 16:22:00.429 +08:00] [INFO] [mysql.go:341] ["Start mysql sink"] [dsn="root@tcp(127.0.0.1:3306)/?interpolateParams=true&loc=Local&multiStatements=true&time_zone=%22Local%22"]
> > ```
> 
> Is the downstream TiDB?
> 
> `Error 1298: Unknown or incorrect time zone: 'Local'` this error is reported by `MySQL57`

Yes, TiDB works well and MySQL raises the error.

**Pull request merged**
