### PR TITLE
*: clean useless code && improvement the code struct

### LINKED ISSUE #2748: unstable test etcdSuite.TestPutAllChangeFeedStatus
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```
[2021-09-05T06:50:11.099Z] FAIL: etcd_test.go:284: etcdSuite.TestPutAllChangeFeedStatus
[2021-09-05T06:50:11.099Z] 
[2021-09-05T06:50:11.099Z] etcd_test.go:321:
[2021-09-05T06:50:11.099Z]     c.Assert(err, check.IsNil)
[2021-09-05T06:50:11.099Z] ... value *errors.withStack = [CDC:ErrPDEtcdAPIError]context deadline exceeded ("[CDC:ErrPDEtcdAPIError]context deadline exceeded")
```

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/3868/pipeline/108#step-201-log-273

TiCDC: https://github.com/pingcap/ticdc/commit/97df39e9bcd14e827480e2ad89cfddb1548ee4a8

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve? 
close #2748 
The tested func and failed test case was deleted in this PR.

### What is changed and how it works?

1. Merge `cdc/kv/etcd.go` into `pkg/etcd/etcd.go` and  delete some useless funcs.
2. Move `cdc/model/reactor_state.go` to `/pkg/orchestrator/reactor_state.go`.

All suggestions welcome！

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by ben1009** [comment]
💪🏻

**Review by overvenus — APPROVED** [review]
LGTM, awesome!

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
