### PR TITLE
cdc/sink: only check max-message-bytes for default protocol & craft protocol

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

When try to create the topic, only check `max-message-bytes` when using the default open protocol or craft protocol.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
None`.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Review by amyangfei — COMMENTED** [review]
Is there any unit test to cover the change

**Comment by 3AceShowHand** [comment]
> Is there any unit test to cover the change

it's quite hard to cover this case in the unit test, since sarama mock broker does not work well in this case,  it's mocked response does not have valid information about what we want, which always making the case fail.

**Pull request merged**
