### PR TITLE
status(dm): fix update mariadb source status

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

fix https://github.com/pingcap/ticdc/issues/3639

### What is changed and how it works?

also set gtid when income gtid is from mariadb

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
     -  start relay with mariadb
     - query-status -s source

```
➜ dmctl query-status  -s mysql-01
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "no sub task started",
            "sourceStatus": {
                "source": "mysql-01",
                "worker": "worker1",
                "result": null,
                "relayStatus": {
                    "masterBinlog": "(upstream1-bin.000002, 463)",
                    "masterBinlogGtid": "0-1-1",
                    "relaySubDir": "0-1.000001",
                    "relayBinlog": "(upstream1-bin.000002, 463)",
                    "relayBinlogGtid": "",
                    "relayCatchUpMaster": true,
                    "stage": "Running",
                    "result": null
                }
            },
            "subTaskStatus": [
            ]
        }
    ]
}
```

Code changes

 - Has exported function/method change

Side effects

Related changes

### Release note 

```release-note
`fix update mariadb source status`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡 @okJiang @lichunzhu

**Comment by okJiang** [comment]
lgtm

**Review by glorv — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Review by lichunzhu — COMMENTED** [review]
When will we set `*Location` incorrectly? 🤔

**Comment by Ehco1996** [comment]
> Why will we set `Location`'s flavor incorrectly at first but need to revise it after a period of time? 🤔

@lichunzhu 

we don't have falvor field for struct `location` and the way we init SourceStatus (`var status binlog.SourceStatus`)will init empty string as gtid so we met this err.

use `binlog.InitLocation(pos, gtidSet)` to init location can fix this problem , added in https://github.com/pingcap/ticdc/pull/3648/commits/f0da6ac59bec7761deb1dde12a4910e2d0c493b4

i think falvor of location's gtid should not be changed, so maybe i should revert [this](https://github.com/pingcap/ticdc/pull/3648/commits/b313a8392a642962af7b32bd15a8a6587bbdf45a)?

**Comment by lichunzhu** [comment]
> this

SGTM

**Comment by lichunzhu** [comment]
> > Why will we set `Location`'s flavor incorrectly at first but need to revise it after a period of time? 🤔
> 
> @lichunzhu
> 
> we don't have flavor field for struct `location` and the way we init SourceStatus (`var status binlog.SourceStatus`)will init empty string as gtid so we met this err.
> 
> use `binlog.InitLocation(pos, gtidSet)` to init location can fix this problem , added in [f0da6ac](https://github.com/pingcap/ticdc/commit/f0da6ac59bec7761deb1dde12a4910e2d0c493b4)
> 
> i think flavor of location's gtid should not be changed, so maybe i should revert [this](https://github.com/pingcap/ticdc/pull/3648/commits/b313a8392a642962af7b32bd15a8a6587bbdf45a)?

SGTM. That would be great

**Comment by lance6716** [comment]
can we merge it or wait some change?

**Pull request merged**
