### PR TITLE
compactor: fix duplicate entry in safemode

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
in https://github.com/pingcap/dm/pull/2061, we change `replace` to `insert on duplicate key update`
but `insert on duplicate key update` will error when there is more than one key duplicate.
.e.g.
```
downstream: (1,1),(2,3)
insert (1,3) on duplicate key update will report duplicate key error
replace(1,3) will delete both rows and insert it
```

### What is changed and how it works?
- use replace instead in safemode
   - insert(safemode) => replace
   - insert => insert
   - update(safemode) => delete + replace
   - update(update pk) => update
   - update(not update pk) => insert on duplicate key update
   - delete => delete

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

to avoid /merge trigger run-all-tests

**Pull request merged**
