### PR TITLE
tests: fix unified_sorter_sort_dir_conflict

### PR DESCRIPTION
**Pull request by liuzix**
### What problem does this PR solve? 
- Unstable test `unified_sorter_sort_dir_conflict`

### What is changed and how it works?
- Use check table instead of sleep to wait for tables to be replicated.

### Check List 

Tests 

 - Integration test

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
Should this PR be picked to other release branches and master

**Review by amyangfei — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by overvenus** [comment]
What a coincide! I rewrited the integration test into unit tests to stabilize the test last night. Check it out https://github.com/pingcap/ticdc/compare/master...overvenus:rewrite-unified-sorter-dir-conflict-test?expand=1

**Review by overvenus — APPROVED** [review]

**Pull request merged**
