### PR TITLE
*: use tiup lib to generate errors toml (#1007)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1007 to release-4.0

---

### What problem does this PR solve? 

This PR introduces the errors documentation generator shipped by tiup to generate the errors.toml according to https://github.com/pingcap/tidb/blob/master/docs/design/2020-05-08-standardize-error-codes-and-messages

DNM until pingcap/tiup#851 merged.

### What is changed and how it works?

Add a make target `errdoc` to check whether the errors.toml is staled.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by leoppro — COMMENTED** [review]
LGTM

**Review by lonng — COMMENTED** [review]
LGTM
(maybe the errors.toml needs to be re-generated if release-4.0 has different errors definition with master)

**Review by lonng — APPROVED** [review]

**Pull request merged**
