### PR TITLE
docs: add design doc template and linter

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

None

### What is changed and how it works?

add design doc template and linter

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

None
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
> If the linter finds invalid formats, will it give some modify advices?

`npm run lint` will check which files are not formatted, but will not output specific changes.` npm run lint:fix` will do the formatting directly. Also `husky` will use git hooks to check for formatting, if the format is not correct you can't do a git local commit.

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

Could you please help me trigger the merge process? Thanks!

**Pull request merged**
