### PR TITLE
sink: split mysql sink into multiple files

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

cc: https://github.com/pingcap/ticdc/issues/2199
After this split is landed, I will collect it into a mysql package.
### What is changed and how it works?

split mysql sink into multiple files.

The original code was organized in a confusing way and I had a hard time reading this part of the code.

1. split mysql wroker
2. split mysql params
3. split mysql syncpoint store
4. rename `parseSinkURI` to `parseSinkURIToParams`
5. rename `configureSinkURI` to `generateDSNByParams`
### Check List 

Tests 

 - No code( only move and rename)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @overvenus @ben1009 

Could you please take a look? Thanks! 

I'm actually not quite sure if these changes should be picked up in the release branch, as it makes a huge adjustment to the structure of the code.

**Review by ben1009 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

Could you please take a look? Thanks!

**Pull request merged**
