### PR TITLE
cdc/sink: Refine sink interface

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve? 
To fix the bug of #3503 , we should manage table checkpoint per table in the sink, this is PR is a part of the fix. In this PR, only change the interface method, no real logic is changed.

### What is changed and how it works?
add table ID to Sink interface, below functions will be changed,
```
type Sink interface {
   FlushRowChangedEvents(ctx context.Context, tableID model.TableID, resolvedTs uint64) (uint64, error)
   Barrier(ctx context.Context, tableID model.TableID) error
}
```

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes
 - Has interface methods change

Side effects

Related changes

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by overvenus** [comment]
Find a flaky test #3626 .

**Pull request merged**
