### PR TITLE
cli(refactor): add changefeed  cmds

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

split from #2482

### What is changed and how it works?

add changefeed statistics cmd.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

adding more cmds.

**Comment by hi-rustin** [comment]
/unhold

Ready for review.

Tested in https://github.com/hi-rustin/ticdc/commit/cec74d38f32af272c12c0374a12da06b36329a89

I marked the merge as `rebase` because it's a big change and each commit is a separate command, so I think we need to keep each commit, and it's also easier for you to review after splitting.

**Review by overvenus — APPROVED** [review]

**Comment by hi-rustin** [comment]
@amyangfei @asddongmen 

Could you please take a look? Thanks!

**Review by ben1009 — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
