### PR TITLE
owner: deprecate the removed changefeed state

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
before this pr, the changefeed state is very complex, now we have simplified the state representation, remove the `Removed` state.

the changefeed state transfer:
ticdc-state-transfer

 ① execute changefeed pause   
 ② execute changefeed resume   
 ③ changefeed throw a recoverable errors  
 ④ execute changefeed resume   
 ⑤ changefeed throw a unrecoverable errors  
 ⑥ The sync task has reached the preset TargetTs and the sync is automatically stopped  

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
Have you check the `removed` state in integration tests.
Besides would you please follow up the related change in utf cases:
- Whether we should update test cases utf according to the state change
- How can we make utf cases compatible with different release versions.

**Comment by ben1009** [comment]
is there any other tests beside ut could verify the compatibility of the change, thx

**Review by amyangfei — APPROVED** [review]

**Review by liuzix — APPROVED** [review]

**Pull request merged**
