### PR TITLE
parser(dm): use TiDB special comment for DROP INDEX IF EXISTS

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/3004

### What is changed and how it works?
as title

### Check List 

Tests 

 - Unit test

Code changes

Side effects

 - Breaking backward compatibility

Related changes

### Release note 

```release-note
Better support MySQL -> TiDB -> MySQL scenario by using TiDB special comment
```

### CODE REVIEW

**Review by Ehco1996 — APPROVED** [review]
LGTM 

some information for other reviewers

* mysql [5.6](https://dev.mysql.com/doc/refman/5.6/en/drop-index.html)/[8.0](https://dev.mysql.com/doc/refman/8.0/en/drop-index.html) does't not support `DROP INDEX IF EXISTS `
* mariadb support this statement but dm not commit to support mariadb as downstream
* tidb support this statement with or without comment

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
