### PR TITLE
logSink: revert defaultBufferChanSize, add a trigger to flush logSink.units when chennal is full

### PR DESCRIPTION
**Pull request by dengqee**
### What problem does this PR solve? 
[1259](https://github.com/pingcap/ticdc/issues/1259) [2424](https://github.com/pingcap/ticdc/issues/2424)

### What is changed and how it works?
Recover `defaultBufferChanSize `to 20480 which increased by [1469](https://github.com/pingcap/ticdc/pull/1469).

Add a criterion for refreshing  logSink.units, which `sendEvents.Load() == defaultBufferChanSize`, i.e. units chennal is full.

### Check List 

Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Possible performance regression
 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
fix a bug where synchronizing large tables to cdclog failed.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
By the way, we lack unit tests in cdc/sink/cdclog, that is quite a problem

**Review by overvenus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
