### PR TITLE
make: add build-failpoint command and fix failpoint build (#1388)

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1388 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In ticdc repo:
git pr https://github.com/pingcap/ticdc/pull/1424
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/ticdc.git pr/1424:release-4.0-395d94a42c4f
```

---

### What problem does this PR solve?

 - add a makefile command: `build-failpoint`, which can help us to build a binary with failpoint-enabled
 - refine `fix_lib_zstd.sh`: change the source code of pulsar client to make sure `github.com/valyala/gozstd` will never be built

### Check List 

Tests 
 - No code

### Release note

- No release note

### CODE REVIEW

**Comment by leoppro** [comment]
LGTM

**Comment by amyangfei** [comment]
should change merge branch?

**Review by leoppro — APPROVED** [review]

**Pull request merged**
