### PR TITLE
tests: add `max-message-bytes` to kafka integration tests

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 

In PR #3080, we change the default `max-message-bytes` from 512M to 1M. Some of our Kafka integration tests would have row data that size larger than 1M.

### What is changed and how it works?
* add `max-message-bytes` to create changefeed in our Kafka integration tests, and set it to 10M

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by ben1009** [comment]
[2021-10-20T14:10:05.960Z] table kafka_message.check1 not exists at last check

**Review by hi-rustin — APPROVED** [review]
Waiting for the CI landed. The changes LGTM.

**Review by ben1009 — APPROVED** [review]

**Comment by hi-rustin** [comment]
CI failed: https://github.com/pingcap/ticdc/issues/3207

**Pull request merged**
