### PR TITLE
github: speed up the arm build

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
 speed up the arm build with setup action.

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes
None

### Release note 

```release-note
None

```

### CODE REVIEW

**Review by lonng — COMMENTED** [review]
/lgtm

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/ticdc/blob/afdc27d1dd5d4725ee14244fc9436f2ab9818000/.github/workflows/check_and_build.yaml#L60 Maybe github.ref != 'refs/heads/main'? Seems we still trigger arm build in pull request.

**Comment by hi-rustin** [comment]
> https://github.com/pingcap/ticdc/blob/afdc27d1dd5d4725ee14244fc9436f2ab9818000/.github/workflows/check_and_build.yaml#L60
> Maybe github.ref != 'refs/heads/main'? Seems we still trigger arm build in pull request.

Maybe == ? If we want to run only in the master push, then I think it should be ==. We do use master, only the new repository is main.

**Comment by hi-rustin** [comment]
[48min -> 3min](https://github.com/pingcap/ticdc/runs/4065861086?check_suite_focus=true), so I think we can trigger it for each event.

**Comment by hi-rustin** [comment]
/cc @lance6716 @gozssky 
Could you please take a look? Thanks!

**Review by Ehco1996 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]

**Pull request merged**
