### PR TITLE
cmd(refactor): add server cmd and cleanup old server and test cmds

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

part of #2168

cc: #2199

split from #2262

### What is changed and how it works?
add server cmd and cleanup old server and version cmds.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 None

Related changes

 Nonement

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

- [ ] tests
- [ ] comments

**Comment by hi-rustin** [comment]
/unhold

Ready for review.

**Comment by hi-rustin** [comment]
/cc @amyangfei  @overvenus 

/uncc lonng

Could you please take a look? Thanks!

**Comment by hi-rustin** [comment]
/hold

There are tests that consistently fail.

**Comment by hi-rustin** [comment]
/unhold

/run-all-tests

Ready for review.

**Review by overvenus — APPROVED** [review]
LGTM

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
