### PR TITLE
cmd: fix typo and stop using deprecated API

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
None

### What is changed and how it works?
fix typo and stop using deprecated API

### Check List 

Tests 

None

Code changes

None

Side effects
None

Related changes

 - Need to cherry-pick to the release branch

### Release note

- No release note

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]
there is another one, in case you would like to change together https://github.com/pingcap/ticdc/blob/dc6de9861aa799996497455e97a8348c9e2d2851/cmd/client_tso.go#L48

**Comment by hi-rustin** [comment]
> there is another one, in case you would like to change together
> 
> https://github.com/pingcap/ticdc/blob/dc6de9861aa799996497455e97a8348c9e2d2851/cmd/client_tso.go#L48

Fixed. Thanks!

**Review by overvenus — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
