### PR TITLE
dm/test: fix openapi test client

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

as title

### What is changed and how it works?
```
"/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/tests/openapi/client/openapi_task_check", line 7

[2021-11-01T14:09:33.373Z] SyntaxError: Non-ASCII character '\xc3' in file /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/tests/openapi/client/openapi_task_check on line 7, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```
`Non-ASCII character` can not read by pyhton2.7 in CI, just remove this not used character, 
i added this character is to test if `Non-ASCII character` would work with openapi in my local machine
 (it works because json can handle `Non-ASCII character`)

### Check List 

Tests 

 - No code

Code changes

- None

Side effects

 - None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
```
 Error: unknown keys in config file /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/ticdc/dm/tests/all_mode/conf/diff_config.toml: [log-level chunk-size sample-percent use-checksum fix-sql-file check-tables check-tables.schema check-tables.tables table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table table-config table-config.schema table-config.table table-config.source-tables table-config.source-tables.instance-id table-config.source-tables.schema table-config.source-tables.table source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id source-db source-db.host source-db.port source-db.user source-db.password source-db.instance-id target-db target-db.host target-db.port target-db.user target-db.password]
```
seems sync_diff change the config format 😂

**Comment by lance6716** [comment]
please specify file encoding, not remove this test

```
# -*- coding: utf-8 -*- 
```

**Comment by Ehco1996** [comment]
> please specify file encoding, not remove this test

in fact this var is not used in current task, but i added a new one in  https://github.com/pingcap/ticdc/commit/4109c378a0335d996cefd2f33491a2f4c3e5ef25

**Review by lance6716 — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Comment by Ehco1996** [comment]
/merge  dm ci tesed in manually
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/232/pipeline/

**Pull request merged**
