### PR TITLE
kafka: partition number can't be negative

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Fix https://github.com/pingcap/ticdc/issues/798

### What is changed and how it works?

Add check to partition number

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by lance6716** [comment]
LGTM

**Comment by amyangfei** [comment]
failed because an error in test case
```
[2020-07-28T09:34:15.592Z] [2020/07/28 17:34:15.247 +08:00] [FATAL] [main.go:183] ["unexpected error when executing sql"] [error="Error 1049: database doesn't exist"] [stack="github.com/pingcap/log.Fatal\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:59\nmain.dml\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:183\nmain.runDDLTest.func2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:87"]
```

**Comment by lance6716** [comment]
> failed because of an error in test case
> 
> ```
> [2020-07-28T09:34:15.592Z] [2020/07/28 17:34:15.247 +08:00] [FATAL] [main.go:183] ["unexpected error when executing sql"] [error="Error 1049: database doesn't exist"] [stack="github.com/pingcap/log.Fatal
>         /go/pkg/mod/github.com/pingcap/log@v0.0.0-20200511115504-543df19646ad/global.go:59
> main.dml
>         /home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:183
> main.runDDLTest.func2
>         /home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/ticdc/tests/multi_source/main.go:87"]
> ```

what's the cause of "db/table doesn't exist"? DM's intergration tests also meet this error 😂

**Pull request merged**
