### PR TITLE
cli: Add NoArgs to all commands

### LINKED ISSUE #2303: cdc cli changefeed create --start-ts does not work properly and may lead to data loss
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

TiCDC cli creates a changefeed that does not use the start-ts specified in command line. It leads to data loss.

image

Note that the start-ts in command line is invalid and it points to 1975-02-25 15:14:19.597000.

```
mysql> select tidb_parse_tso(426318359552065537); # start-ts in cli output

+------------------------------------+
| tidb_parse_tso(426318359552065537) |
+------------------------------------+
| 2021-07-14 23:11:20.469000         |
+------------------------------------+

mysql> select tidb_parse_tso(42610054816776198); # start-ts in command line

+-----------------------------------+
| tidb_parse_tso(42610054816776198) |
+-----------------------------------+
| 1975-02-25 15:14:19.597000        |
+-----------------------------------+
```

2. What did you expect to see?

  a. create a changefeed with a start-ts specified in command line.
  b. report warnings about invalid start-ts. 

3. What did you see instead?

A wrong changefeed is created and it leads to data loss. 

4. Versions of the cluster

v5.0.1

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
close #2303 
close https://github.com/pingcap/ticdc/issues/1706

### What is changed and how it works?
add noArgs to all commands 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

/hold
/cc

### CODE REVIEW

**Comment by hi-rustin** [comment]
block by https://github.com/spf13/cobra/issues/1480

**Comment by hi-rustin** [comment]
/auto-cc

Ready for review!

**Comment by hi-rustin** [comment]
/cc @asddongmen 

Could you please take a look? Thanks!

**Review by asddongmen — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
