### PR TITLE
dep(dm): update go-mysql

### LINKED ISSUE #3847: DM sync phase is failed by `Start sync error: invalid sequence 8 != 1`
### What did you do?

https://asktug.com/t/topic/274148

also, my local mysql 8.0.19 meet same error. 

https://github.com/go-mysql-org/go-mysql/issues/535 can fix this problem

### What did you expect to see?

no error

### What did you see instead?

`Start sync error: invalid sequence 8 != 1`

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve? 
close #3847 
close https://github.com/pingcap/ticdc/issues/3419

### What is changed and how it works?
update dependency to include the fix

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
fix a bug that DM may report "invalid sequence" when upstream is MySQL 8.0
fix a bug that upstream will die on SHOW SLAVE HOSTS
```

### CODE REVIEW

**Review by Ehco1996 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

I'll update go-mysql again to include https://github.com/go-mysql-org/go-mysql/pull/655 tomorrow

**Comment by lance6716** [comment]
/hold

```
ERROR 2027 (HY000) at line 1: Malformed packet
```

strange that I can't reproduce it locally

**Pull request merged**
