### PR TITLE
bug-fix: fix duplicate key for insert with compactor is enabled

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
In the original design, I imagined that insert, delete, and update would be executed with the order of delete, replace, and update. But now we use causality after compactor to execute in the original order and insert will not become replace(insert on duplicate update) unless safemode is true. So we need to explicitly set the safemode to true for delete + insert = insert.

### What is changed and how it works?
- set safemode for delete + insert = insert
- fix the originnal unstable test

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
cc @lance6716 @Ehco1996 @glorv

**Review by glorv — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

wait dm-integration-test to pass

**Comment by lance6716** [comment]
```
[2021-11-01T08:41:04.886Z]     import requests
[2021-11-01T08:41:04.886Z] ImportError: No module named requests
```

😵 

also there's make fmt needed @GMHDBJD

**Pull request merged**
