### PR TITLE
kv/client: support reconnect regions when no event received too long

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Solve https://github.com/pingcap/ticdc/issues/1586 (This is the master PR, release-5.0 PR is https://github.com/pingcap/ticdc/pull/1589)

NOTE, **need discussion**: 

1. The check only workers after region is initialized, is this reasonable.
2. The reconnect interval (15m) is hard coded, we need to discuss whether to add a config in server config file

After discussion

1. Keep check after the region is initialized, because the incremental scan phase could cost long.
2. We don't need to add it in server config file, since the check is only in real time data phase.

### What is changed and how it works?

- Reuse kv event aliveness check in lock resolver tick
- If a region doesn't receive any event for more than `15 minutes`, force the gRPC stream to reconnect
- Only update the kv client v1, kv client v2 will be updated later

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- Force the gRPC stream to reconnect if no event (including resolved ts event) is received for more than 15 minutes.

### CODE REVIEW

**Comment by amyangfei** [comment]
This is master PR, PTAL too, thx @leoppro @liuzix

**Review by leoppro — APPROVED** [review]

**Comment by amyangfei** [comment]
The integration test relys on #1553

**Pull request merged**
