### PR TITLE
build: upgrade to go1.16.4

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

ref: https://github.com/pingcap/ticdc/issues/1769

### What is changed and how it works?

build ticdc with go1.16, note ticdc is still compatible with go version >= 1.13

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Comment by ben1009** [comment]
/ looks gtm

**Comment by tisonkun** [comment]
@amyangfei can we close #1769 by this pull request?

**Comment by tisonkun** [comment]
.. and do we really want to cherry-pick to 4.0 and 5.0? I think we only update the pipeline on master.

**Comment by tisonkun** [comment]
ok I can see that both cherry-pick prs are closed.

**Pull request merged**
