### PR TITLE
*: add config file for server (#1493)

### LINKED ISSUE #1257: Support an extensible config provider for cdc server
## Feature Request

**Is your feature request related to a problem? Please describe:**

  `cdc` server has many command line parameters and there will be more parameters in the future. It is not a good choice to add all these parameters in the command line, for the following reasons:

  -  TiCDC could be deployed via `TiUP` or `TiDB operator`, existing parameters are hardcoded in these two deployment tools, adding new parameters is not extensible
  - It is better to keep important, essential parameters in the command line only, and hide some advanced/minor parameters into a config provider (via config file or config center or something else)

**Describe the feature you'd like:**

  - [ ] Provide an extensible way to add a parameter of cdc server. Some solution candidates
         - toml config file, which is same as TiDB/PD/TiKV. We prefer this choice
         - use PD(etcd) as a config center
  - [ ] Arrange current parameters cdc server, simplify command line parameters, and put other parameters into the new config provider.

**Teachability, Documentation, Adoption, Migration Strategy:**

   Current cdc server parameters

```
➜  ./cdc server -h
Start a TiCDC capture server

Usage:
  cdc server [flags]

Flags:
      --addr string                           Set the listening address (default "127.0.0.1:8300")
      --advertise-addr string                 Set the advertise listening address for client communication
      --ca string                             CA certificate path for TLS connection
      --cert string                           Certificate path for TLS connection
      --cert-allowed-cn ,                     Verify caller's identity (cert Common Name). Use , to separate multiple CN
      --gc-ttl int                            CDC GC safepoint TTL duration, specified in seconds (default 86400)
  -h, --help                                  help for server
      --key string                            Private key path for TLS connection
      --log-file string                       log file path
      --log-level string                      log level (etc: debug|info|warn|error) (default "info")
      --owner-flush-interval duration         owner flushes changefeed status interval (default 200ms)
      --pd string                             Set the PD endpoints to use. Use ',' to separate multiple PDs (default "http://127.0.0.1:2379")
      --processor-flush-interval duration     processor flushes task status interval (default 100ms)
      --sorter-chunk-size-limit uint          size of heaps for sorting (default 1073741824)
      --sorter-max-memory-consumption uint    maximum memory consumption of in-memory sort (default 17179869184)
      --sorter-max-memory-percentage int      system memory usage threshold for forcing in-disk sort (default 90)
      --sorter-num-concurrent-worker int      sorter concurrency level (default 4)
      --sorter-num-workerpool-goroutine int   sorter workerpool size (default 16)
      --tz string                             Specify time zone of TiCDC cluster (default "System")
```

### PR DESCRIPTION
**Pull request by ti-srebot**
cherry-pick #1493 to release-4.0
You can switch your code base to this Pull Request by using [git-extras](https://github.com/tj/git-extras):
```bash
# In ticdc repo:
git pr https://github.com/pingcap/ticdc/pull/1518
```

After apply modifications, you can push your change to this PR via:
```bash
git push git@github.com:ti-srebot/ticdc.git pr/1518:release-4.0-9e58fbbc7d37
```

---

### What problem does this PR solve? 
add config file for server close #1257

add a flag named `config` to set the server config file path:
```
➜  ticdc git:(server_config) ✗ ./bin/cdc server --help
Start a TiCDC capture server

Usage:
  cdc server [flags]

Flags:
      --addr string                           Set the listening address (default "127.0.0.1:8300")
      --advertise-addr string                 Set the advertise listening address for client communication
      --ca string                             CA certificate path for TLS connection
      --cert string                           Certificate path for TLS connection
      --cert-allowed-cn ,                     Verify caller's identity (cert Common Name). Use , to separate multiple CN
      --config string                         Path of the configuration file

       ......
```

the server config format like this:
```

# TiCDC Server 监听的地址，默认：127.0.0.1:8300
# the listening address of TiCDC server, default: 127.0.0.1:8300
addr = "127.0.0.1:8300"

# 用于客户端建立连接的对外公开的地址，这个地址会被注册到 PD, 默认：和 addr 相同
# the advertise listening address for client communication, this address will be registered to the PD, default: same with the addr item
advertise-addr = "127.0.0.1:8300"

# 日志文件路径
# log file path
log-file = "/tmp/ticdc/ticdc.log"

# 日志级别 (debug|info|warn|error) 默认："info"
# log level (debug|info|warn|error) default: "info"
log-level = "info"

# CDC GC safepoint TTL，以秒为单位，默认：86400(24H)
# CDC GC safepoint TTL duration, specified in seconds, default: 86400(24H)
# gc-ttl = 86400

# TiCDC 集群的时区，默认： "System"
# the time zone of TiCDC cluster, default: "System"
# tz = "System"

[security]
# ca-path = ""
# cert-path = ""
# key-path = ""
# cert-allowed-cn = ["cn1","cn2"]

```

### Check List 

Tests 

 - Unit test

### Release note

- add a config file for ticdc server

### CODE REVIEW

**Comment by liuzix** [comment]
LGTM

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
won't merge this PR until v4.0.13

**Pull request merged**
