### PR TITLE
lint: add shfmt to format sh scripts

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/2670

### What is changed and how it works?
add shfmt to format sh scripts

### Check List 

Tests 

 - Integration test

Code changes
None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
/assign @amyangfei 

Could you please help trigger the merge process? Thanks!

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
@amyangfei  Resolved the conflict, please help trigger again. Thanks!  💚 💙 💜 💛 ❤️

**Pull request merged**
